### PR TITLE
Add test template for atbash cipher

### LINKED ISSUE #1928: atbash-cipher: add test template
## Task
Create a test template file for `atbash-cipher`

### Details
1. If this is your first time contributing to this repository, welcome!
    - Contributing to a repository on GitHub requires a [fork](https://help.github.com/en/articles/fork-a-repo)
1. Create a branch on your local repository called `atbash-cipher-add-test-template`
    - Run: `git checkout -b atbash-cipher-add-test-template`
1. Clone problem-specifications repository; this is used to populate the template
    - Run: `git clone https://github.com/exercism/problem-specifications ../problem-specifications`
1. Create `exercises/atbash-cipher/.meta/template.j2`
    - See [Generator Documentation] for more information
1. Generate test file from new template
    - Run: `bin/generate_tests.py atbash-cipher`

At this point, if the generator fails, or you are otherwise stuck,
please feel free to reach out! It is perfectly acceptable to submit
an incomplete PR in order to get feedback or assistance.

### Resources
- [Contributing Guide]
- [Generator Documentation]
- [Closing issues using keywords]

[Contributing Guide]: https://github.com/exercism/python/blob/master/docs/CONTRIBUTING.md
[Generator Documentation]: https://github.com/exercism/python/blob/master/docs/GENERATOR.md
[Closing issues using keywords]: https://help.github.com/en/articles/closing-issues-using-keywords

### PR DESCRIPTION
**Pull request by tqa236**
Resolve #1928.

There's a track specific test that is not included yet. I also don't see that this test is quite interesting or relevant. What do you think about it?

### CODE REVIEW

**Comment by yawpitch** [comment]
I'm okay with losing the roundtrip as well.

Tangent, but why are we using `assertMultiLineEqual` when none of the strings are multiple lines? Also since we've dropped support for 2 and 3.4 is our minimum 3 we could just switch back to `assertEqual`, which uses `assertMultiLineEqual` under the hood for strings anyway.

**Comment by tqa236** [comment]
I don't know the difference between these two so I use the one in the old test file. Should I switch to `assertEqual` now?

**Comment by yawpitch** [comment]
I'd say so ... @cmccandless we got anything running < 3.4 on CI?

**Comment by cmccandless** [comment]
> we got anything running < 3.4 on CI?

Not anymore, no.

**Comment by tqa236** [comment]
Is this PR ready to be merged or should I modify anything?

**Pull request merged**
