### PR TITLE
pig-latin: update tests to version 1.1.0

### LINKED ISSUE #1019: pig-latin: update tests to version 1.1.0
As identified in #784, some of the exercise test-suites are out-of-date, `pig-latin` is one of them. It would therefore be really helpful for people to go through and update the test suite to match the canonical data.

Tests should typically be ordered according to their order in the canonical data, since this makes it easier to check and update them in future. If you think that there's a better order, please let us know your reasoning in your PR.

If there are some additional tests that currently exist in this track but which aren't in the canonical data, these can be kept if you think that they are useful. They should be placed at the bottom of the test cases, and it would also be super-helpful if you could add a comment before them saying `# Additional tests for this track` to make it clear that they aren't part of the canonical data.

The version string should be placed just before the first test class and followed by a blank line. For this exercise, the version string is:
```
# Tests adapted from `problem-specifications//canonical-data.json` @ v1.1.0
```

**Test suite:** [exercism/python/exercises/pig-latin/pig_latin_test.py](https://github.com/exercism/python/blob/master/exercises/pig-latin/pig_latin_test.py)
**Canonical data:** [exercism/problem-specifications/exercises/pig-latin/canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/pig-latin/canonical-data.json)

### PR DESCRIPTION
**Pull request by kishan3**
Resolves #1019

### CODE REVIEW

**Comment by cmccandless** [comment]
@kishan3 Thanks for your pull request! In order to merge your changes, the example solution (`example.py`) must also be updated to pass the new tests. Please make the appropriate changes.

**Comment by kishan3** [comment]
@cmccandless not sure how can I do that. Can you help for it?

**Comment by N-Parsons** [comment]
Thanks for your work @kishan3! It just needed a slight tweak to the regex for consonant sounds.

My solution was to treat `y` as a vowel in the simplest case (`[^aeiouy]`) and then add a test for `y` followed by a vowel (`y(?=[aeiou])`). The construct `(?=[aeiou])` does a lookahead for `[aeiou]` but is non-capturing, meaning that the vowels go into the second group. If you want to learn more about regex, I would suggest looking in the [Python docs](https://docs.python.org/3/library/re.html).

**Comment by kishan3** [comment]
Thank you, sir @N-Parsons. Learned many things from you.

**Pull request merged**
