### PR TITLE
🤖 Add .meta/config.json file for concepts

### PR DESCRIPTION
**Pull request by ErikSchierboom**
_TL;DR; Add authors/contributors to a new `concepts/<slug>/.meta/config.json` to Concepts in the same way you have for Concept Exercises._

---

To properly attribute authorship/contributorship for an individual concept, each concept will have its own `.meta/config.json` file with `authors` and `contributors` keys like those for concept and practice exercises. We're also moving the concept's blurb from the track's `config.json` to the `.meta/config.json` file, also similar to concept and practice exercises.

See https://github.com/exercism/docs/pull/96/files for the update to the specification.

This PR adds a `.meta/config.json` file for all concepts found in the track's `config.json` file containing:

- A `blurb` key, which value is copied from the `config.json` file and subsequently removed from the `config.json` file
- An `authors` key, the value of which is copied from the exercise teaching the concept (if any)
- A `contributors` key, the value of which is copied from the exercise teaching the concept (if any)

**For ease, the concept's authors/contributors are pre-populated with the authors/contributors of the exercise that teaches the concept (if any).**

## Maintainers TODO list

These are the things you, the maintainers, should do:

- [ ] Update the authors (if needed) 
- [ ] Update the contributors (if needed)

**For clarity, authors should be the people who originally created the concept documents on this track. Contributors should be people who have substantially contributed to the concept documents. PRs for typos or multiple-concept PRs do not automatically mean someone should be considered a contributor to that concept. Those non-concept-specific contributions will get recognition through Exercism's reputation system in v3.**

You can either update this PR by pushing a new commit to this PR, or merge this and do a follow-up PR later. The former has the disadvantage that once we've added linting rules to `configlet` for the concept `.meta/config.json` file, the configlet CI check will start failing. 

## Tracking

https://github.com/exercism/v3-launch/issues/27

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
Following a suggestion that was made, we've updated the PR to pre-populate the authors/contributors with the authors/contributors of the exercise that teaches the concept (if any). This gives us a nice starting point, as the concept documents used to be exercise documents. You, the maintainers, should check to see if the authors/contributors are correct and add missing authors/contributors.

**Comment by BethanyG** [comment]
@ErikSchierboom  -- apologies for not getting to this sooner.  I think we are probably better off adding these in manually ourselves.  I recently put in stubs for our renamed and identified concepts (see [here](https://github.com/exercism/python/tree/main/concepts), and deleted mis-named or outdated ones.  Many of the ones I deleted are present in this PR -- and all of the stubs I made are not (t_hey're not explicitly linked to concept exercises yet._)

I will go in this weekend and make sure that the 11 concept exercises we do have have the appropriate references, and I will manually add the stubs for the other concept directories.  Maybe once that's done, we can figure out if there are any holes?  But I think this PR as it stands probably shouldn't be merged.

**Comment by BethanyG** [comment]
Here is the PR for the stub files: [2398](https://github.com/exercism/python/pull/2398)
Here is the PR for the `concepts` related to existing `concept exercises`: [2399](https://github.com/exercism/python/pull/2399)

**Comment by ErikSchierboom** [comment]
@BethanyG Sure. Whatever you prefer

**Pull request closed without merging**
