### PR TITLE
[list-ops]: change `//` to `/` and swap `foldr` arg order

### PR DESCRIPTION
**Pull request by IsaacG**
[Related Forum Discussion here](https://forum.exercism.org/t/bug-in-python-list-ops-test/4835/31).

### CODE REVIEW

**Comment by BethanyG** [comment]
@IsaacG  -- you should add your name as a contributor to this exercise.  😄

**Comment by BethanyG** [comment]
Can we also put in a comment in the JinJa2 template to maybe remind the next set of folx (_more than likely our future selves_) why we're swapping arguments?  I just think that this will come up again, so any places we can comment for posterity will be helpful.  [JinJa2 Comments](https://tedboy.github.io/jinja2/templ5.html).

**Comment by IsaacG** [comment]
> Can we also put in a comment in the JinJa2 template to maybe remind the next set of folx (_more than likely our future selves_) why we're swapping arguments? I just think that this will come up again, so any places we can comment for posterity will be helpful. [JinJa2 Comments](https://tedboy.github.io/jinja2/templ5.html).

Sure! I can add that once I get homen in a few hours. 

> If we are going to break existing solutions, I would vastly prefer to have foldr & foldl both be (acc, el), so that foldl is consistent with Haskell tradition. But I am going to go with your first PR, so we can be done with this debate. 😄

That was actually my first commit. That approach is simpler (less code, no need to swap, no need for a comment). I'm happy to do that, too. It's closer to what is in the problem spec.

**Comment by IsaacG** [comment]
I added a comment to the JinJa2 template.

If you prefer `func(acc, el)`, #3405 does that.

**Comment by BethanyG** [comment]
Alright.  I am going to go with #3405, and close this one in favor of that.  @IsaacG -- can you add yourself as an exercise contributor to that PR?  As soon as that is done, I'll approve and merge.  Many thanks!

**Pull request closed without merging**
