### PR TITLE
config.json: Fix invalid UUIDs

### PR DESCRIPTION
**Pull request by nywilken**
This change pertains to https://github.com/exercism/configlet/issues/99

### CODE REVIEW

**Comment by N-Parsons** [comment]
Hi @nywilken, thanks for the PR. I'm a little bit confused though.

exercism/configlet#99 seems to be suggesting that 8-4-4-4-12 is the correct format (which is what your PR does), but the latest release copy of `configlet` is currently generating 8-4-4-4-19. Is this just due to the recent change to `google/uuid` that hasn't been made into a release yet?

**Comment by nywilken** [comment]
> exercism/configlet#99 seems to be suggesting that 8-4-4-4-12 is the correct format (which is what your PR does), but the latest release copy of configlet is currently generating 8-4-4-4-19. Is this just due to the recent change to google/uuid that hasn't been made into a release yet?

Hi @N-Parsons, that’s exactly the case. It was an oversight on my end so I stopped creating new UUID repair PRs for the moment and started work to get a new configlet release out. My apologies for not communicating that info in the PR. Feel free to hold on this PR until configlet is released.

**Comment by nywilken** [comment]
@N-Parsons the latest release of Configlet [v3.6.1](https://github.com/exercism/configlet/releases) is now available for download. 

I went ahead and updated this PR with the latest changes from master and fixed the UUID for the `simple-linked-list` exercise as well. This PR should be good to go now. Please let me know if you have any questions.

**Comment by N-Parsons** [comment]
Thanks, @nywilken

**Pull request merged**
