### PR TITLE
bracket-push: Update the param name to clarify further to users

### LINKED ISSUE #548: bracket-push: add parameters to exercise placeholder
We would like you to help us add expected parameters in placeholder templates as described in #509 to make it easier for learners to start working on the exercise in question.

Feel free to ask any questions, we'll be glad to help!

### PR DESCRIPTION
**Pull request by atg-abhishek**
…erences Issue #548

-----
Resolves #548

### CODE REVIEW

**Comment by atg-abhishek** [comment]
How about just `input_string`, it makes it a little clearer while not being terribly long? Also, I'll change the commit message in the new commit if you like this idea for the param name

**Comment by JanKaifer** [comment]
If just `string` is unclear than you can just shorten your long name to `bracket_string`.

**Comment by m-a-ge** [comment]
I'm voting for `input_string` 📝

**Comment by atg-abhishek** [comment]
I've pushed a new commit addressing the comments above

**Comment by m-a-ge** [comment]
@atg-abhishek merged, thanks!

It's a best practice to squash your commits https://github.com/exercism/docs/blob/master/contributing/git-basics.md#squashing. It isn't a big deal since I can do it myself, but it would be awesome to just click on 'Merge pull request' button 😃

Just for future reference a guide of how to write good commit messages - https://chris.beams.io/posts/git-commit/#seven-rules

**Pull request merged**
