### PR TITLE
Knapsack: add template.j2

### PR DESCRIPTION
**Pull request by lucasdpau**
knapsack_test.py named the class ChangeTest, but I followed specifications that said exercise:knapsack, so if this runs properly the class should be named Knapsack.

However, I was unable to properly test if it works. I tried to bin/generate_tests.py but it said "ERROR:generator:the black utility must be installed"

I installed black v19.3b0 through pip but it still didn't work, and I got same message. So if this doesn't work I'd appreciate help!

### CODE REVIEW

**Comment by cmccandless** [comment]
Can you please provide the full output of the following commands?

`which python3.7`

`python3.7 -m pip list | grep black`

`black --version`

`bin/generate_tests.py -v knapsack`

**Comment by lucasdpau** [comment]
I'm using windows so those commands don't work, but I can give you outputs for similar commands, let me know if these are helpful enough

C:\Users\Lucas>where python
C:\Users\Lucas\AppData\Local\Programs\Python\Python37-32\python.exe

C:\Users\Lucas>python -m pip list | findstr black
black        19.3b0

C:\Users\Lucas\AppData\Local\Programs\Python\Python37-32\Scripts>black --version
black, version 19.3b0

C:\Users\Lucas\Desktop\Developer\Hacktoberfest 2019\python\bin>generate_tests.py -v knapsack
ERROR:generator:the black utility must be installed

**Comment by yawpitch** [comment]
Could you please run `where black` as well, now we know you’re on Windows?

**Comment by lucasdpau** [comment]
C:\Users\Lucas>WHERE /R c:\ black
c:\Users\Lucas\AppData\Local\Programs\Python\Python37-32\Scripts\black.exe

**Comment by yawpitch** [comment]
Hmm, can you also try `python -c “import shutil; print(shutil.which(‘black’))”`? And then `python -c “import shutil; print(shutil.which(‘black.exe’))”`?

**Comment by lucasdpau** [comment]
Both of them gave me None.

However this line of questioning got me to add 
c:\Users\Lucas\AppData\Local\Programs\Python\Python37-32\Scripts 
to my PATH.

After that I get:
C:\Users\Lucas>python -c "import shutil; print(shutil.which('black'))"
C:\Users\Lucas\AppData\Local\Programs\Python\Python37-32\Scripts\black.EXE

and 

C:\Users\Lucas>python -c "import shutil; print(shutil.which('black.exe'))"
C:\Users\Lucas\AppData\Local\Programs\Python\Python37-32\Scripts\black.exe

So perhaps that was the solution?

**Comment by yawpitch** [comment]
That should fix it... for the script to work `black` must be callable directly, which means `black.exe` has to be on your PATH... bit surprised that `pip install` didn’t do that for you.

**Comment by lucasdpau** [comment]
Yea what a hassle, but thanks for the help! We ended up figuring out the problem but it looks like this test template has been made by someone else in the meantime. I'll checkout another problem and hopefully things work out better.

**Pull request closed without merging**
