### PR TITLE
isogram: update tests to version 1.2.0 (#1016)

### PR DESCRIPTION
**Pull request by abhijitparida**
#hacktoberfest

### CODE REVIEW

**Comment by N-Parsons** [comment]
Thanks @abhijitparida, looks perfect!

In future, you can help make things easier by adding some magic words to you PR description (eg. `resolves #1016`) so that the corresponding issue can be automatically closed when we merge your changes. You can find out more about magic words at: [https://help.github.com/articles/closing-issues-using-keywords/](https://help.github.com/articles/closing-issues-using-keywords/)

**Comment by N-Parsons** [comment]
Hi @abhijitparida, it looks like you just pushed more changes to your branch. Each Pull Request needs to be based on it's own branch, so that the changes can be submitted and looked at separately.

**Comment by abhijitparida** [comment]
Thanks for the heads up. Should I close this PR and create new ones?

**Comment by N-Parsons** [comment]
There are some fancy ways to do it, but the easiest solution is probably to copy out your changes and `git reset --hard` to before your commits, then create new branches to put your changes in.

If you check `git log` it should give you a list of recent commits, and then you can copy the hash of the most recent one before yours and run `git reset --hard <hash>`.

**Pull request closed without merging**
