### PR TITLE
[Matching Brackets] draft approaches

### PR DESCRIPTION
**Pull request by colinleach**
This one ended up less short and boring than I expected, with benchmarking totally invalidating my predictions!

As an aside, this is the second approaches submission that needs to refer to Walrus operators - now occurring regularly in community solutions. Whatever the low current priority of the learning syllabus, it would make my life easier to have PR #3585 merged so that we can reference it.

### CODE REVIEW

**Comment by colinleach** [comment]
Do you have any idea why `configlet` has started insisting that `.articles/performance/snippet.md` must exist and can't be empty? It seems a bit silly.

**Comment by BethanyG** [comment]
> Do you have any idea why `configlet` has started insisting that `.articles/performance/snippet.md` must exist and can't be empty? It seems a bit silly.

No clue, really.  Probably trying to be "helpful" by linting.  A question for Erik, methinks.

**Comment by colinleach** [comment]
OK, thanks. I'll put something on the forum.

**Comment by colinleach** [comment]
Welcome back! I am, as usual, very happy with your changes.

**Review by colinleach — COMMENTED** [review]
I'm happy with these changes

**Comment by BethanyG** [comment]
Tryin' to make my way back, slowly.  😅 .  Just about done with this, and after one more once-over, will approve and merge!

**Comment by colinleach** [comment]
In your own time. Let me know if there's anything I can do to help.

I'm also feeling my way back in. Today's submission (julia/two-bucket) was my first solution for >2 months.

**Comment by BethanyG** [comment]
Alrighty.  Let's hope that I didn't re-confuse left vs right.  I **think** everything's all good...so pushing the big, green button!  🚀

**Comment by BethanyG** [comment]
WOOT!  One down, 17 more to go.......

**Comment by colinleach** [comment]
Yeah, I don't think I'll PR any more just yet (for ___so___ many reasons)

**Pull request merged**
