### PR TITLE
binary-search: Update the tests following the canonical data

### PR DESCRIPTION
**Pull request by elyssonmr**
Update the `binary-search` track following the recommendations from issue #989

### CODE REVIEW

**Comment by cmccandless** [comment]
@elyssonmr Thanks for your pull request!

Travis-CI build failed due to code style violations:
```Bash
$ flake8
./exercises/binary-search/binary_search_test.py:6:1: E302 expected 2 blank lines, found 1
```

**Comment by elyssonmr** [comment]
OK, going to check as soon as I arrive home

**Comment by elyssonmr** [comment]
@cmccandless Done.

**Comment by N-Parsons** [comment]
Hi @elyssonmr, thanks for your work on this.

Unfortunately there was already an open PR for the same issue (#1024) - it was poorly named and didn't reference the corresponding issue, so I'm not surprised that you didn't see it. Since I have now merged the other PR, I'm going to go ahead and close this one.

**Comment by elyssonmr** [comment]
No, prob I saw the notification.
thank you!

**Pull request closed without merging**
