### PR TITLE
Removed footer macros, generated test file and run

### PR DESCRIPTION
**Pull request by gelbelle**

### CODE REVIEW

**Comment by BethanyG** [comment]
WOOOT!  Thank you for this (_and all your hard work on the git-foo_).  🌟 🚀

**Review by BethanyG — APPROVED** [review]

**Comment by gelbelle** [comment]
All the footers are done, test files regenerated, and examples checked against new tests.

**Comment by BethanyG** [comment]
@gelbelle  - _**Many thanks!**_. 🌟 🌈 

Unfortunately, due to delays with work related to #3373, I don't know when we'll be able to merge this.
#3423 & #3419 are also pending the changes discussed in #3373.

**Comment by BethanyG** [comment]
@gelbelle  - WOAH.  Just realized that you pushed these updates to your last branch/PR. 😱  **These should be in several new branches/PRs** -- we don't want all 114 files in one change.  At most (as discussed) we would have 3-5 exercise changes per PR.

I know this is a small change - but it's easer for rollback (_and for fixing CI failures_)  if we sub-group these instead of doing them in a large chunk like this.  Many thanks.

**Review by BethanyG — CHANGES_REQUESTED** [review]
@gelbelle  - per comment, please break this up into several PRs.  At most, we'd like 3-5 exercises per PR.  I know it is a PITA, but these are easier (and safer) to sub-group, rather than doing everything in one branch/PR.  Thanks. 💙

**Comment by BethanyG** [comment]
Thanks for the individual PRs!  I've reopened them, but do have to mark them as "Do not merge" until we get #3373 all tested and merged.

Meanwhile, I will close this behemoth.  😄

**Pull request closed without merging**
