### PR TITLE
[WIP] Implement excercise custom-set

### LINKED ISSUE #746: custom-set: implement exercise
There are exercises that are not yet implemented in Python track (the full list of them - https://github.com/exercism/python/issues/417#issuecomment-334841778).
You can help us change this situation by implementing this one. Ref #417

The guide ["Implement an exercise from specification"](https://github.com/exercism/docs/blob/master/you-can-help/implement-an-exercise-from-specification.md) will help you succeed.

If you still have questions, I encourage you to ask them before starting working on the issue.

I also suggest claiming the issue by creating an empty PR as stated [here](https://github.com/exercism/docs/blob/master/you-can-help/implement-an-exercise-from-specification.md#avoiding-duplicate-work)

Please note that there are some special ['closing issue' keywords](https://help.github.com/articles/closing-issues-using-keywords/) that you can put in description of your PR and Github will take care of closing the corresponding issue automatically after merge.
This simple thing helps us a lot, and makes our life a bit easier

### PR DESCRIPTION
**Pull request by prakashdanish**
Resolves #746

### CODE REVIEW

**Comment by m-a-ge** [comment]
@prakashdanish, are you still working on this?

**Comment by prakashdanish** [comment]
@m-a-ge yes, but It'll take some time, I've got some project going on. I hope that's not a problem.

**Comment by cmccandless** [comment]
@prakashdanish if you are too busy to work on this, please close this PR to allow someone else to work on it.

**Comment by N-Parsons** [comment]
I'm going to go ahead and close this due to inactivity. If you still want to work on this, I'd welcome a new PR when you have some more free time.

**Pull request closed without merging**
