### PR TITLE
add template with expected parameter to grep exercise

### LINKED ISSUE #561: grep: add parameters to exercise placeholder
We would like you to help us add expected parameters in placeholder templates as described in #509 to make it easier for learners to start working on the exercise in question.

Feel free to ask any questions, we'll be glad to help!

### PR DESCRIPTION
**Pull request by carloscdias**
Fix issue #561 

Fixes #561

### CODE REVIEW

**Comment by behrtam** [comment]
Thanks for your work! Could you please improve your commit message. Please have a look at our [README](https://github.com/exercism/python#pull-requests).

**Comment by carloscdias** [comment]
Thanks for the feedback @behrtam 
Please, let me know if I can do anything else

**Comment by m-a-ge** [comment]
Thanks, @carloscdias

Please note that there are some special ['closing issue' keywords](https://help.github.com/articles/closing-issues-using-keywords/) that you can put in description of your PR and Github will take care of closing the corresponding issue automatically after merge. 
It makes our work much easier. I hope this hint will help you to make your future PRs a bit better

Just for future reference, a good guide of writing good commit messages https://chris.beams.io/posts/git-commit/#seven-rules

**Comment by carloscdias** [comment]
Thanks, @m-a-ge 

I appreciate the hint, sorry I missed it this time.

**Comment by m-a-ge** [comment]
@carloscdias no worries and I hope to see your future PRs 😉

**Pull request merged**
