### PR TITLE
binary-search-tree: Implement exercise binary-search-tree

### PR DESCRIPTION
**Pull request by hernan940730**
Implement binary-search-tree and test cases.

Solves #740

### CODE REVIEW

**Comment by m-a-ge** [comment]
There was already opened PR #773
Did you miss it?

**Comment by hernan940730** [comment]
OMG, I didn't see it.

I have a question though, why I'm getting this?
image

**Comment by Teo-ShaoWei** [comment]
You will need to insert an entry of `binary-search-tree` into `config.json`. Do open the file and give it a look. The exercise order is important and reflects the order which Exercism pushes exercises out via `exercism fetch python`.

You can copy the entry from another track that already have `binary-search-tree` implemented so as to not reinvent the wheel, but you do need to generate a new UUID using `bin/configlet uuid` I think...

**Comment by hernan940730** [comment]
Thank you @Teo-ShaoWei it was what you say!

**Comment by cmccandless** [comment]
@hernan940730 @m-a-ge as this is a duplicate of #773 , I am going to close this PR.

**Pull request closed without merging**
