### PR TITLE
Bob approaches fixes

### PR DESCRIPTION
**Pull request by bobahop**
Fixes

- snake case names
- removes leading underscore and private info
- adds info on tuples

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]
LGTM @BethanyG could you check if the comments you made previously have been addressed?

**Review by BethanyG — APPROVED** [review]
I think there is a stray `isShout` ref in the final couple prose paragraphs, and  `isShout` | `isQuestion`  in the table header.  Beyond that, LGTM.

There are a couple of other approaches I can think of, but both would probably be over engineered (using an answers `dict` and structural pattern matching).  If I get inspired, I'll file a follow-on PR.  🙂

**Comment by BethanyG** [comment]
P.S.  Leaving unmerged in case you want to fix those last three things.  But feel free to merge at will.

**Comment by ErikSchierboom** [comment]
> There are a couple of other approaches I can think of, but both would probably be over engineered & slow (using an answers dict and structural pattern matching). If I get inspired, I'll file a follow-on PR. 

Sounds like they'd make for excellent approaches 😉

**Review by ErikSchierboom — APPROVED** [review]
LGTM! All occurances of `isShout` and `isQuestion` have been fixed

**Pull request merged**
