### PR TITLE
Replace stale link by working link with valuable informtion

### PR DESCRIPTION
**Pull request by mominfaruk**
@BethanyG Thanks for reviewing my pull request and for your feedback! I've made the changes to the stale link based on the is issue #3389. Whereas I have checked the preview of the url and added the preview title under the link by updating the description.

### CODE REVIEW

**Comment by BethanyG** [comment]
@mominfaruk  -- Thank you!  I've reopened this, and the CI is currently running.  I'll give it a review here shortly.

**Review by BethanyG — CHANGES_REQUESTED** [review]
Apologies - I got sidetracked by meetings and was unable to review until now.  Made one URL change - it is the same URL, but it expands and goes straight to the SO accepted answer.  Other than that (which you need to accept or not) this looks good! Thank you for submitting it.

**Review by BethanyG — APPROVED** [review]
Realized I could do the commit -- so I went ahead!  Thanks again for doing this change.  🌟 🌈

**Comment by mominfaruk** [comment]
Thanks for the commit. Much appreciate

**Pull request merged**
