### PR TITLE
Run skipped tests

### LINKED ISSUE #391: Run skipped tests
The **allergies** exercise has an additional [test case](https://github.com/exercism/xpython/blob/master/exercises/allergies/allergies_test.py#L35-L37) which is skipped. If the tests get executed with the `.test/check-exercises.py` script during the travis build, even skipped tests should be run.

### PR DESCRIPTION
**Pull request by rootulp**
Resolves #391
Inspiration from [Skipping tests in unittests](https://sateeshkumarb.wordpress.com/2011/06/16/skipping-tests-in-unittests/)

### CODE REVIEW

**Comment by behrtam** [comment]
Oh, that looks great. I will look at it more closely tomorrow when there is more time.

*Note: The max line length in this repo is relaxing 99 instead of 79 ... (https://github.com/exercism/xpython/blob/master/.travis.yml#L21)

**Comment by behrtam** [comment]
The convention (maybe because of GNU *getopt*) is that single letter options are 
preceded by single dash and multi-letter options are preceded by double dash.
So could you make a small cosmetic change `-extra_credit` -> `--extra-credit`

I played with `skipUnless` at some point but I missed the `sys.argv.remove` hack.

**Comment by rootulp** [comment]
> So could you make a small cosmetic change -extra_credit -> --extra-credit

I think this is a great change!

> I played with skipUnless at some point but I missed the sys.argv.remove hack.

I agree this does seem hacky. Basically we don't want to pass any sys.args to unittest but I couldn't find a better way to do this. Please let me know if you have any ideas.

>Don't know but do you think we should add a blue print for this to the README or
somewhere else if someone in the future also wants to add skipped tests or do you
think they will find it in the existing exercises?
Ad

The README currently doesn't have any docs on writing tests so I'm not sure where this would go. In the short-term I think contributors can use these two exercises as a template but I agree - this should be documented somewhere.

**Comment by behrtam** [comment]
Well instead of removing the value from `sys.argv` you could pass an explicit argument vector like this:
```python
if __name__ == '__main__':
    unittest.main(argv=[''])
```

**Comment by behrtam** [comment]
There is also a way that works without changing the existing test code by monkey-patching the `unittest.skip` decorator and using the test *discovery* modus.

```
$ python exercises/allergies/allergies_test.py
...s...
----------------------------------------------------------------------
Ran 7 tests in 0.001s

OK (skipped=1)

$ python -c "import unittest as u; u.skip = lambda r: lambda t: t; u.main(None, argv=['', 'discover', '-p', '*test.py', '/Users/tmo/github/exercism/xpython/exercises/allergies/'])"
.......
----------------------------------------------------------------------
Ran 7 tests in 0.001s

OK
```

**Comment by rootulp** [comment]
I'm comfortable with both approaches. The monkey patching approach has the benefit of not maintaining an `EXTRA_CREDIT_ASSIGNMENTS` list. Also exercise implementers are free to create optional tests using any pattern.

On the other hand, the `--extra-credit` approach forces exercise implementers to conform to using the following pattern:
```python
@unittest.skipUnless('--extra-credit' in sys.argv, 'Skipping Extra Credit')
```
which would lead to consistency between exercises. This way users can always run optional test with the `--extra-credit` flag.

**Comment by rootulp** [comment]
@behrtam any updates here?

**Comment by behrtam** [comment]
Should find some time at the weekend to look at this again.

**Pull request closed without merging**
