### PR TITLE
[WIP] Zipper add test template

### PR DESCRIPTION
**Pull request by tsamoglou**
`{%- if tree_obj is null-%}
null
` 
jinja2.exceptions.TemplateAssertionError: no test named 'null'

what can I do to see if tree_object == null????

### CODE REVIEW

**Comment by cmccandless** [comment]
The correct syntax is:
`{%- if tree_object is none -%}`

**Comment by tsamoglou** [comment]
> The correct syntax is:
> `{%- if tree_object is none -%}`

Yeah but in canonical data of zipper in atribbute left the value is null not none 
@cmccandless

**Comment by cmccandless** [comment]
When Python loads JSON objects, null becomes `None`

**Comment by tsamoglou** [comment]
Thank you for your responding I will make the changes @cmccandless

**Pull request closed without merging**
