### PR TITLE
[Unpacking & Multiple Assignment/Locomotive Engineer]: Added Some Notes on Using `*` On the Left-Hand Side

### PR DESCRIPTION
**Pull request by BethanyG**
[Forum Discussion](https://forum.exercism.org/t/potential-for-expansion-of-packing-to-list-syntax-explanation/13824/4).

Didn't add a whole lot here, but I hope it helps without confusing things.

### CODE REVIEW

**Comment by chivalry** [comment]
I think this does a nice job of, first, pointing out the trailing comma for the user, and second, pointing the user to more information if needed. tyvm, @BethanyG.

**Comment by ErikSchierboom** [comment]
> @ErikSchierboom -- ok to merge?

Looks good, but why are you asking me? :D

**Comment by BethanyG** [comment]
Apologies!  I should have been clearer in my note.  This was one of three PRs that tested your [bot fix](https://forum.exercism.org/t/no-important-files-changed-action-not-firing/13673/12).

Rather than just doing test PRs, this one and [PR 3825](https://github.com/exercism/python/pull/3825) are "live" changes.  [PR 3827](https://github.com/exercism/python/pull/3827) is test-only.

Just wondering when to merge/close and revert [PR 3824](https://github.com/exercism/python/pull/3824).

**Comment by ErikSchierboom** [comment]
@BethanyG I think the behavior is correct here! Thanks for the test! 

As for the actual merging, feel free to do whatever you like :)

**Pull request merged**
