### PR TITLE
complex-numbers: operator overloading

### PR DESCRIPTION
**Pull request by susg**
WIP for https://github.com/exercism/python/issues/724

### CODE REVIEW

**Comment by cmccandless** [comment]
This is going to have some substantial conflicts with work being done in #1057  for #993 . I still think that keeping the two requests separate is the right thing to do. 

@m-a-ge @N-Parsons Since the changes here are more trivial than those in #1057, I recommend holding off on merging changes here until after #1057 has been merged. 

@susg , you may want to wait to continue working on this until #1057 has been merged as some work may have to be redone because #1057 re-orders several test cases.

**Comment by m-a-ge** [comment]
@susg #1057 was merged, could you please resolve the conflicts and look into code style issues?
```text
3.23s$ flake8
./exercises/complex-numbers/complex_numbers.py:6:13: W291 trailing whitespace
./exercises/complex-numbers/complex_numbers.py:7:1: W293 blank line contains whitespace
./exercises/complex-numbers/complex_numbers_test.py:9:1: E302 expected 2 blank lines, found 1
./exercises/complex-numbers/complex_numbers_test.py:38:35: E231 missing whitespace after ','
./exercises/complex-numbers/complex_numbers_test.py:40:1: W293 blank line contains whitespace
./exercises/complex-numbers/complex_numbers_test.py:44:35: E231 missing whitespace after ','
./exercises/complex-numbers/complex_numbers_test.py:50:35: E231 missing whitespace after ','
./exercises/complex-numbers/complex_numbers_test.py:52:1: W293 blank line contains whitespace
./exercises/complex-numbers/complex_numbers_test.py:56:35: E231 missing whitespace after ','
./exercises/complex-numbers/complex_numbers_test.py:62:35: E231 missing whitespace after ','
./exercises/complex-numbers/complex_numbers_test.py:68:35: E231 missing whitespace after ','
./exercises/complex-numbers/complex_numbers_test.py:74:37: E231 missing whitespace after ','
```

**Comment by cmccandless** [comment]
As this is no longer pending resolution of #1057, I am removing the `pinned` label.

**Comment by susg** [comment]
Hi, I have created another [pull request](https://github.com/exercism/python/pull/1098), as I was unable to rebase the changes with my current branch. I hope it is not an issue.

**Comment by m-a-ge** [comment]
@susg it is certainly not the end of the world here, but at work they'll expect from you that you can rebase or update your PRs (force push for example) without any problems. So, I suggest spending some time and learn how it can be done
Ref to a new PR #1098

**Comment by N-Parsons** [comment]
I'm going to go ahead and close this in favour of your newer PR: #1098.

**Pull request closed without merging**
