### PR TITLE
Normalize the config file to minimize noise later

### PR DESCRIPTION
**Pull request by kytrinyx**
We will be scripting a number of changes to the track configuration.
This runs configlet fmt, which ensures that any further changes can be minimized.

See https://github.com/exercism/meta/issues/95

### CODE REVIEW

**Comment by lucifer-angel** [comment]
update

**Comment by N-Parsons** [comment]
I've had a look at the changes, and I think that these changes harm human-readability too much and should be re-evaluated. I'm not too bothered about the changes to the `maintainers.json`, since that file is significantly smaller and is interacted with far less than the `config.json`, but I would still prefer to maintain the current key ordering.

**Comment by m-a-ge** [comment]
@cmccandless for me its format is fine, it isn't typically read by most people (other than maintainers).
I believe it's very important to have consistency and I don't think it's worth changing anything in how it's formatted

**Comment by kytrinyx** [comment]
@N-Parsons @cmccandless @m-a-ge I agree that the readability is harmed by alphabetizing the keys. We've got a discussion going in exercism/meta#95 - please join in there / follow along. Once we get everything sorted, I'll resubmit this.

**Pull request closed without merging**
