### PR TITLE
Test generator: filter test cases using tests.toml

### PR DESCRIPTION
**Pull request by cmccandless**
Recommend using a normal Merge commit instead of squashing, as there are commits here for separate exercises.

Normally, I would have committed those dedicated branches, but the other changes here required the exercises to be updated to pass CI.

### CODE REVIEW

**Review by ErikSchierboom — APPROVED** [review]
LGTM (I don't know Python though)

**Comment by cmccandless** [comment]
@ErikSchierboom I figured I'd tag you in just in case you were tracking somewhere which language tracks had up-to-date test generators.

**Review by BethanyG — APPROVED** [review]
`generate_tests.py` & `generator_macros.j2` look good to me.  I am going to also spot-check the problems, but I probably won't look at every single one.

**Comment by ErikSchierboom** [comment]
Thanks for the tag @cmccandless! I appreciate it.

**Pull request merged**
