### PR TITLE
Update CI test runner for v3

### PR DESCRIPTION
**Pull request by cmccandless**
- Check for exemplar.py (>=v3), then example.py (<v3)
	- See https://github.com/exercism/v3/pull/3086
- Use pathlib instead of os.path

### CODE REVIEW

**Comment by cmccandless** [comment]
Maintainer note: squash when merging

**Review by BethanyG — COMMENTED** [review]
This looks good to me -- but with two questions:

1.  Is our `master` branch going to be renamed `main`?  If so, we'll need to change the ref.
2. Should we hold this merge until after the "explosion"?  We have some pending exercise PRs to finish up.

Otherwise, I think we are good to go 🌟

**Comment by cmccandless** [comment]
> Is our master branch going to be renamed main? If so, we'll need to change the ref.

I've added main to target branches

> Should we hold this merge until after the "explosion"? We have some pending exercise PRs to finish up.

I don't think that's necessary. If 'exemplar.py' is missing, it looks next for 'example.py', so this should be backwards compatible.

**Review by BethanyG — APPROVED** [review]
👍🏽

**Pull request merged**
