### PR TITLE
Update and reformat all READMEs

### PR DESCRIPTION
**Pull request by N-Parsons**
I found it weird that the "Submitting Exercises" was at heading level 3 in the README, since this sometimes meant that it appeared to be a subheading of something unrelated.

This PR updates all exercises, as well as the insert used for automated generation of READMEs.

### CODE REVIEW

**Comment by m-a-ge** [comment]
@N-Parsons did you regenerated it with `configlet` or use your own tooling?

**Comment by N-Parsons** [comment]
@m-a-ge, I did it with a Python script as a quick solution.

I just took a look with the `configlet` (it's surprisingly easy to use!) and there are a few minor changes in a lot of the READMEs (removal of white-space, slight rewords, etc.) and 9 need closer work due to significant changes or issues with the upstream `problem-specifications`. I'm happy to go through and fix them, so I've marked this PR as WIP until I have these resolved - I should have some time this weekend.

**Comment by m-a-ge** [comment]
@N-Parsons thanks a lot for working on this!

**Comment by N-Parsons** [comment]
@m-a-ge, I think it's finished now!

**Comment by m-a-ge** [comment]
@N-Parsons fell free to merge it at will

**Pull request merged**
