### PR TITLE
Add parameters to exercise placeholder

### PR DESCRIPTION
**Pull request by AllanNozomu**
Solves issues (539 - 547)
- [allergies](#539)
- [alphametics](#540)
- [anagram](#541)
- [atbase-cipher](#542)
- [beer-song](#543)
- [binary](#544)
- [binary-search](#545)
- [bob](#546)
- [book-store](#547)

I think the [bracket-push](#548) don't need a parameter, since the name string is good for this case.

I renamed the parameter to the names used in example.py

### CODE REVIEW

**Comment by JanKaifer** [comment]
Hi @AllanNozomu,
could you please create for each exercise new PR and name it "exercise_name: your change description".
It's contribution rule here 😄.

**Comment by m-a-ge** [comment]
Hi, @AllanNozomu. I'm glad to see your PR.

Please note, as I mentioned in #631 (comment), I've intentionally created a separate issue for each exercise for the following reasons:

1. to encourage new contributions and promote Exercism during Hacktoberfest
1. having a separate issue for each exercise makes it easier to review them and discuss changes
1. it's relatively easier to track the progress that way in #509

It was tempting to solve all the issues in one PR, but it's hard to review it. I hope you'll understand the decision.

**Comment by AllanNozomu** [comment]
Sorry, about that, I will close this PR

**Comment by m-a-ge** [comment]
@AllanNozomu no worries and thanks for your understanding 😄

**Pull request closed without merging**
