### PR TITLE
allergies: replace assertFalse with assertIs

### PR DESCRIPTION
**Pull request by olufotebig**
* replace assertFalse with assertIs because the test passes if the tested method returns None
* replace assertTrue with assertIs for consistency.

### CODE REVIEW

**Comment by N-Parsons** [comment]
In case you're wondering what the error is (I got curious and checked :P), it's that `example.py` is returning an `int` instead of a `bool`, which works fine with `assertFalse`, but not `assertIs`. The easy solution is to add `bool()` on the return statement for `Allergies.is_allergic_to`.

**Comment by N-Parsons** [comment]
@olufotebig, don't forget to update `example.py` so that this passes the tests and can be merged :)

**Comment by olufotebig** [comment]
Let do that now

**Comment by m-a-ge** [comment]
Thanks, @olufotebig

**Pull request merged**
