### PR TITLE
Call black as a lib instead of an external tool

### PR DESCRIPTION
**Pull request by dvermd**
This PR shows how to use black as a lib instead of an external tool which needs a process to be spawned.
It results on a 0,25s performance improvement on my machine.

One thing to consider for this PR is that black is still tagged as beta. Its CLI API used today may be less prone to change than its internal API.
Hope this still help.

### CODE REVIEW

**Comment by yawpitch** [comment]
To be honest I'd be more comfortable relying on the CLI interface, as they've not documented the use as a library and the CLI seems to be the only thing they have any investment in maintaining as stable. The most recent change on the reformat_one interface completely re-ordered arguments, and while that was 8 months ago I'd not be confident it wouldn't happen again.

**Comment by yawpitch** [comment]
@cmccandless what do you think?

**Comment by cmccandless** [comment]
I'm inclined to keep using the CLI. That seems to be the standard recommended usage.

**Comment by dvermd** [comment]
I understand your position and maintenance anticipation. 
Though this PR won't make it to master, I had fun reading through black source code and integrating it.

**Comment by cmccandless** [comment]
In academic interest: do your changes also cause the generator to exit with a non-zero code if black fails to format the file (most common case for this is invalid Python). If not, that might be a fun exercise as well.

**Comment by dvermd** [comment]
You're right, it did not exit with non-zero code and I just fixed it to.

**Comment by cmccandless** [comment]
Another possibility for avoiding the subprocess spin-up per exercise:

https://github.com/psf/black#blackd

**Comment by dvermd** [comment]
Launching blackd is one spawn, this optimization would only be interested when generating many/all exercises ? 
Would that be of any interest for exercism/python to have that ? 
Anyway, I might give it a try to play with requests or pycurl.

**Comment by yawpitch** [comment]
There _might_ be an argument for `blackd` in the CI process worker when building _many_ tests ... but realistically reducing the call overhead is not a priority.

**Pull request closed without merging**
