### PR TITLE
fix typo in the instruction of guidos-gorgeous

### PR DESCRIPTION
**Pull request by thuvh**
- remove double in

### CODE REVIEW

**Review by BethanyG — COMMENTED** [review]
Thanks for the catch!

**Comment by thuvh** [comment]
I create forum link: https://forum.exercism.org/t/fix-typo-in-the-instruction-of-guidos-gorgeous/4571

**Comment by iHiD** [comment]
I've updated this here: #3366

(@ErikSchierboom Do we have a way of reassigning the rep etc to @thuvh?)

**Comment by ErikSchierboom** [comment]
@iHiD We can do an arbitrary rep token, but it would not show up as the "right" contribution I think

**Pull request closed without merging**
