### PR TITLE
grep: add test template

### LINKED ISSUE #1953: grep: add test template
## Task
Create a test template file for `grep`

### Details
1. If this is your first time contributing to this repository, welcome!
    - Contributing to a repository on GitHub requires a [fork](https://help.github.com/en/articles/fork-a-repo)
1. Create a branch on your local repository called `grep-add-test-template`
    - Run: `git checkout -b grep-add-test-template`
1. Clone problem-specifications repository; this is used to populate the template
    - Run: `git clone https://github.com/exercism/problem-specifications ../problem-specifications`
1. Create `exercises/grep/.meta/template.j2`
    - See [Generator Documentation] for more information
1. Generate test file from new template
    - Run: `bin/generate_tests.py grep`

At this point, if the generator fails, or you are otherwise stuck,
please feel free to reach out! It is perfectly acceptable to submit
an incomplete PR in order to get feedback or assistance.

### Resources
- [Contributing Guide]
- [Generator Documentation]
- [Closing issues using keywords]

[Contributing Guide]: https://github.com/exercism/python/blob/master/docs/CONTRIBUTING.md
[Generator Documentation]: https://github.com/exercism/python/blob/master/docs/GENERATOR.md
[Closing issues using keywords]: https://help.github.com/en/articles/closing-issues-using-keywords

### PR DESCRIPTION
**Pull request by beatorizu**
Add template to generate grep tests. Open the PR not to lose the deadline :D

Resolves #1953

### CODE REVIEW

**Comment by cmccandless** [comment]
This one slipped between the cracks; I'll review in the next couple of days.

**Comment by beatorizu** [comment]
I have not finished this one yet :/

**Comment by cmccandless** [comment]
So there's an issue with the Travis build. This is related to #1920, and not a fault of the PR author:
```
DEBUG:generator:grade-school: attempting render
DEBUG:generator:grade-school: writing render to tmp file /tmp/tmp_fu38o9p
DEBUG:generator:grade-school: formatting tmp file /tmp/tmp_fu38o9p
DEBUG:generator:grade-school: ##### DIFF START #####
DEBUG:generator:--- [current] grade_school_test.py
DEBUG:generator:+++ [generated] /tmp/tmp_fu38o9p
DEBUG:generator:@@ -2,7 +2,7 @@
DEBUG:generator:
DEBUG:generator:from grade_school import School
DEBUG:generator:
DEBUG:generator:-# Tests adapted from `problem-specifications//canonical-data.json` @ v1.0.0
DEBUG:generator:+# Tests adapted from `problem-specifications//canonical-data.json` @ v1.0.1
DEBUG:generator:
DEBUG:generator:
DEBUG:generator:class GradeSchoolTest(unittest.TestCase):
DEBUG:generator:grade-school: ##### DIFF END #####
ERROR:generator:grade-school: check failed; tests must be regenerated with bin/generate_tests.py
DEBUG:generator:grade-school: removing tmp file /tmp/tmp_fu38o9p
```

I'll address this tomorrow; it is late in my timezone.

**Comment by cmccandless** [comment]
@beatorizu 
Good work on a passing template! This is an exercise with a bit higher complexity, and it can be a challenge to get everything quite right.

I took the liberty of refactoring your template a bit. We support per-exercise plugins to the generator as of #2097, so I moved things around to use that so we don't litter generate_tests.py with stuff only needed by single exercises. I've also changed the structure of this a bit to completely use generated content for filenames, so if the files change in the future we're prepared for that.

Thoughts?

**Comment by beatorizu** [comment]
Looks great to me. The code and template are cleaner, and removed hard-code too.

**Pull request merged**
