### PR TITLE
[Lasagna]: Added docstring and fixed format

### PR DESCRIPTION
**Pull request by Metallifax**
Fixed and under-indentation from lines 9-15 in exemplar. Added a module level docstring in both stub and exemplar files.

### CODE REVIEW

**Comment by Metallifax** [comment]
And while I'm here, is there a way that contribute many more changes at once or are we better off going one concept at a time? I'd be comfortable doing many changes in a branch but I'll take it under advisement.

Another thing, I noticed that in this exercise that the dashes are missing from the docstring param and return lines after the type in both files, example:

```
:param elapsed_bake_time: int baking time already elapsed.
:return: int remaining bake time derived from 'EXPECTED_BAKE_TIME'.
```
as opposed to 

```
:param elapsed_bake_time: int - baking time already elapsed.
:return: int - remaining bake time derived from 'EXPECTED_BAKE_TIME'.
```

Just to be certain, from what I gathered from #2974, you said you could take them or leave them, but I also get the argument that they can look noisy to the reader. Easy fix, but I'm the same, take it or leave it kind of deal. Let me know what you think.

**Comment by BethanyG** [comment]
@Metallifax - Thank you so much for this.  Sincere apologies for not replying sooner. I'm a bit swamped, so won't be able to review until the weekend.

>Just to be certain, from what I gathered from https://github.com/exercism/python/issues/2974, you said you could take them or leave them, but I also get the argument that they can look noisy to the reader. Easy fix, but I'm the same, take it or leave it kind of deal. Let me know what you think.

I know its an _answer_ you want, but I remain strongly ambivalent.  😆   I truly will go with whatever feels right to you.  The only thing I am really "allergic" to is the use of a colon, since that symbol sets off the params.

>And while I'm here, is there a way that contribute many more changes at once or are we better off going one concept at a time? I'd be comfortable doing many changes in a branch but I'll take it under advisement.

I think as long as you keep that branch up to date with things that are merged into `main` (and your PR description is clear), we should have no issues.  Normally, we'd want changes for each exercise in their own PRs, but since these are stubs and docstrings, I think its fine to put them all in one group.  That might also make it easier to make them more consistent.  Just keep your eyes peeled for changes to `main`.  Merge conflicts are not as fun as you might think.  😉 

And I will be around at the weekend, should you have any questions or issues or need help.  ✨

**Comment by Metallifax** [comment]
Another possible change I noticed is the spacing between the `# TODO:` lines and the functions:

```python
# TODO: define the 'EXPECTED_BAKE_TIME' constant
# TODO: consider defining the 'PREPARATION_TIME' constant
#       equal to the time it takes to prepare a single layer


# TODO: define the 'bake_time_remaining()' function
def bake_time_remaining():
    """Calculate the bake time remaining.
    ...
```

Double space between `PREPERATION_TIME` and the `bake_time_remaining()` TODO

```python
    ...
    based on the `EXPECTED_BAKE_TIME`.
    """

    pass

# TODO: define the 'preparation_time_in_minutes()' function
#       and consider using 'PREPARATION_TIME' here

# TODO: define the 'elapsed_time_in_minutes()' function
```

Single space between the rest. 

My reasoning stems from the two blank lines between functions and classes rule ([E302](https://www.flake8rules.com/rules/E302.html)), but hey, this is the first exercise so how much that really matters is debatable.

**Comment by BethanyG** [comment]
Hi @Metallifax - I am soooo sorry at the delay!  😱   Really really swamped with things.

>Should I make my own branch after this PR goes through or just reuse an older one and pull the newer changes on that? I'm used to working on branches in my private repositories where I can freely branch at my leisure, but I assume the rules change a bit in a production repo -- would love the advice when time allows. TIA.

I'd do a fresh one.  Maybe name it for the [issue](https://github.com/exercism/python/issues/2974) we have open for docstrings?  That helps remind me what it's for.  😄 

Because you don't have write access to the repo, the easiest workflow is to [fork and then branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks).  That way, you can push to your fork, and open an PR from there.

To answer your questions about the TODOs:

for this one
```python
# TODO: define the 'EXPECTED_BAKE_TIME' constant
# TODO: consider defining the 'PREPARATION_TIME' constant
#       equal to the time it takes to prepare a single layer


# TODO: define the 'bake_time_remaining()' function
def bake_time_remaining():
    """Calculate the bake time remaining.
 ```

My logic was that the top 2 TODOs were module-level constants, so I wanted more space between them and the rest of the TODOs and functions in the file.  But if it's looking odd to you, you can go ahead and change it.  😄   I trust your judgement on this one.

**Comment by Metallifax** [comment]
@BethanyG Thanks for the reply and I appreciate the trust. I'll follow your tips on branching and include the spacing change of this exercise as one of the items the be patched. I'm working on portfolio stuff in preparation for

**Pull request merged**
