### PR TITLE
[Ellen's Alien Game/Classes Concept]: Change Dunder Methods Link in `introduction.md` and `about.md`

### PR DESCRIPTION
**Pull request by oezg**
https://mathspp.com/blog/pydonts/dunder-methods
is better than the existing link.
The existing link does not explain so much
https://dataindependent.com/glossary/double-underscore-dunder/

### CODE REVIEW

**Comment by BethanyG** [comment]
Hi @oezg 👋🏽 

Thanks for this. 😄  In addition to not being as informative, that link is now erroring!

However, before we can merge this, we should also update the `classes` [concept `about.md`](https://github.com/exercism/python/blob/main/concepts/classes/about.md) file.  Could you add that update that to this PR?

**Review by BethanyG — CHANGES_REQUESTED** [review]
As described in my last comment, could you check the other files and add changes as necessary?  _Many thanks!_

**Comment by BethanyG** [comment]
@oezg -- are you still interested in completing this PR?  Please let me know, thanks!

**Comment by oezg** [comment]
Hi Bethany,
yes I am interested in completing this PR. It will be the first PR I will
complete. I must first figure out what I must do for it. Other than that I
am very excited and thank you for the opportunity to complete this PR!
Best regards, Özgür

**Comment by BethanyG** [comment]
@oezg  -- I am going to go ahead and close this PR.  Should you want to finish it, please let me know, and I will reopen.  Thanks!

**Pull request closed without merging**
