### PR TITLE
complex-numbers: Add test template

### PR DESCRIPTION
**Pull request by mbbroberg**
Use the template provided by [this documentation](https://github.com/exercism/python/blob/master/docs/GENERATOR.md). That's as far as I've gotten with it due to errors mentioned in the issue (#1937).

### CODE REVIEW

**Comment by cmccandless** [comment]
The documentation you referenced also says that you will need to look at the canonical-data.json for the exercise to determine the exact layout of the template. Were you able to locate the canonical-data.json file?

**Comment by mbbroberg** [comment]
@cmccandless I haven't found a file by that name: 

```
$ cd python/
$ find . -name "canonical.json"
``` 

What am I missing?

**Comment by cmccandless** [comment]
It doesn't exist in this repository. [Please clone the problem-specifications repository](https://github.com/exercism/python/blob/master/docs/GENERATOR.md#script-usage).

**Comment by mbbroberg** [comment]
:man_facepalming: I searched without `*`s in the `..` directory :man_facepalming:. Thanks!

**Comment by mbbroberg** [comment]
I did the necessary cloning @cmccandless, but still receiving the same error messages: 

```
$ pwd
/home/me/dev/python
$ ls ../problem-specifications/exercises/complex-numbers/canonical-data.json 
../problem-specifications/exercises/complex-numbers/canonical-data.json
$ bin/generate_tests.py -v complex-numbers
INFO:generator:complex-numbers: attempting render
DEBUG:generator:'dict object' has no attribute 'input'
ERROR:generator:complex-numbers: generation failed
```

I'm missing something.

**Comment by cmccandless** [comment]
You need to check the structure of the canonical-data.json for this exercise. The *example* template from the docs will not necessarily match every exercise.

**Pull request closed without merging**
