### PR TITLE
[Card Games]: Added summary first line sentences to docstrings

### PR DESCRIPTION
**Pull request by Metallifax**
- Continuation changes based on #2947.

### CODE REVIEW

**Comment by Metallifax** [comment]
@BethanyG No worries on the response time, I'm just grateful for the experience (not to sound like a broken record, as a first year CS student it's a big deal 🙂). 

I agree that short and sweet as the PEP257 doc outlines is safer and in line with the idea of how a professional looking code base should be. I can attest to Exercism helping me understand important practices seen in a real application, such as the TDD cycle, proper variable naming and code readability, so the docstrings are a great opportunity to show students how to properly document their methods so that others can more easily work with their code.

I did notice that the last changes we made to "Making the Grade" do have some weak voicing issues -- if you'd like I can go ahead and make a separate pull request after we're finished here to keep the momentum up.

And thanks again for the friendly feedback, I'm keeping notes as we go along so that we can get it close to perfect the first time, this has been an awesome first series of changes and I appreciate the patient guidance.

**Review by Metallifax — COMMENTED** [review]
Perfect -- I made the exemplar changes to the stub file locally and pushed that so we should be all set. Thanks again!

**Comment by BethanyG** [comment]
> _I did notice that the last changes we made to "Making the Grade" do have some weak voicing issues -- if you'd like I can go ahead and make a separate pull request after we're finished here to keep the momentum up._

Sure!  Let's do that.  😄   I am happy to work with you, as long as it's helping you learn, and doesn't take up too much of your energy.

**Comment by Metallifax** [comment]
@BethanyG Coding is super therapeutic for me, so it has the opposite effect. I'll go ahead and get that rolling!

**Review by BethanyG — APPROVED** [review]
@Metallifax  - awesome!  🌟   Thanks for doing these.

**Comment by BethanyG** [comment]
@Metallifax  -- _My Apologies!!_  Per Isaacs comment on the last PR -- its _imperative_ voice.  🤦🏽‍♀️ .  So I need to ask you to PR removing the leading `s` for most of these. _Sigh._ Promise going forward these will be smoother. 😄 

Thought I could "eyeball" them .. but we probably should use a checker to make sure.    [pydocstyle](https://github.com/PyCQA/pydocstyle) is a good open-source one.  

Sadly, PyCharm does not integrate this check (_another bug that's been open for them a while_).  It does have a plugin for [kite](https://help.kite.com/article/66-using-the-intellij-pycharm-plugin) - although your milage may vary there.  When I have used kite in the past, it was both slow and very annoying with requests to upgrade to a paid plan.

**Pull request merged**
