### PR TITLE
[list-ops]: change // to / and make have foldl/foldr call func(acc, el), consistent with the problem spec

### PR DESCRIPTION
**Pull request by IsaacG**

### CODE REVIEW

**Comment by BethanyG** [comment]
@IsaacG  -- Thank you for this.  Pls remember to add yourself as an exercise contributor.  After that, I will approve and merge.

**Comment by IsaacG** [comment]
> @IsaacG -- Thank you for this. Pls remember to add yourself as an exercise contributor. After that, I will approve and merge.

Done. Thanks!

**Review by BethanyG — APPROVED** [review]

**Comment by asarkar** [comment]
The arguments to the lambda are inconsistent with the problem description.

> foldr (given a function, a list, and an initial accumulator, fold (reduce) each item into the accumulator from the right using function(item, accumulator));

```
    def test_foldr_direction_dependent_function_applied_to_non_empty_list(self):
        self.assertEqual(foldr(lambda acc, el: el / acc, [1, 2, 3, 4], 24), 9)
```

The first argument to the lambda should be `el`, not `acc`.

**Comment by BethanyG** [comment]
@asarkar - if you'd like to report an issue, please do so on our [forum](https://forum.exercism.org/).  A long-closed PR is not the place to do it.  Thanks.

**Pull request merged**
