### PR TITLE
[Ellens Alien Game] Split files

### PR DESCRIPTION
**Pull request by PaulT89**
See Issue #2992

As expected, the tests choked.  Thoughts?

### CODE REVIEW

**Comment by PaulT89** [comment]
Actually, new idea - keep the exemplar as-is (it's there for mentors anyway), and split the actual exercise files.

**Comment by BethanyG** [comment]
Yeah. I don't think this strategy works.  When I said "fence", I meant a `try/except` in the test file, not splitting into multiple code and test files.  We'll need to do something else.  Apologies that I was not clearer with that in my issue comment.

**Comment by BethanyG** [comment]
Splitting the files (stub or exemplar) is going to lead to the same failure.  Our test runner is not expecting to have to test sequentially.  It can cope with importing something from somewhere else...but the file under test needs to be ONE file.  Maybe someday it will..but not today.  But additionally, I don't think two files improves understanding - I think that adds student confusion.

My thoughts are wrapping the imports in a `try/except` and also putting a TODO in the stub.  Maybe also being pointed in the directions.  See the tests for [Guidos Gorgeous Lasagna](https://github.com/exercism/python/blob/main/exercises/concept/guidos-gorgeous-lasagna/lasagna_test.py) for an example of what I meant by wrapping, or "fencing".

**Comment by PaulT89** [comment]
Oh well, I guess I'm out of ideas then.  Sorry.

**Comment by BethanyG** [comment]
Ok.  Thank you for trying tho.  🙂   Apologies I can't alter the test runner at this time.  When I have a chance, I will PR what I am thinking, and ask you for feedback, if you'd like?

**Comment by PaulT89** [comment]
I'm not sure I'd be able to contribute much - I don't know much of anything about test-runners

**Comment by BethanyG** [comment]
It would be a change to the test file for the exercise, and possibly the task descriptions and intro.  I am not going to change the test runner to be multi-solution file at this time. 🙂

**Comment by PaulT89** [comment]
Okay, well, I guess I'll try to help in whatever way I can.

**Pull request closed without merging**
