### PR TITLE
[New Workflow]: PR-Commenter Part 1/2

### PR DESCRIPTION
**Pull request by J08K**
The new PR-Commenter for the repo, codename: `Porcupine Revenger`. Made together with @BethanyG ❤️ 

Splitting this into two parts, for sharing of REP purposes.

**DO NOT MERGE** until PR #2707 has been merged.

### CODE REVIEW

**Review by BethanyG — APPROVED** [review]
🌟   🌈   _Thank you for all your work on this._  Much appriciated!

**Comment by BethanyG** [comment]
Uh - oh.  @J08K  -- any chance you can do some fetch + rebase magic to resolve the conflicts?  Let me know...or I can try from my side....

**Comment by BethanyG** [comment]
@J08K -- Apologies. I cannot effectively rebase this.  Could you see if you can resolve the merge conflicts in your fork?

**Review by BethanyG — APPROVED** [review]

**Comment by J08K** [comment]
Closing this issue, because some weird stuff is happening with merge conflicts... Note to self: Be scared when you see so many commits that shouldn't be there.

**Pull request closed without merging**
