### PR TITLE
scale-generator: a new test added

### PR DESCRIPTION
**Pull request by nikamirrr**
Done

### CODE REVIEW

**Comment by nikamirrr** [comment]
done

**Comment by m-a-ge** [comment]
@nikamirrr, is this PR related to any issue or test case in question is in `canonical-data.json` for the exercise and that's the reason you've added it?

**Comment by nikamirrr** [comment]
If the test is auto-generated, then likely the cause is there. Not sure how to check.

**Comment by m-a-ge** [comment]
Ok, I've checked `problem-specification` repo for this exercise and `canonical-data.json` is missing there - https://github.com/exercism/problem-specifications/tree/master/exercises/scale-generator
I am not familiar with that exercise to be honest, should get more context.

@nikamirrr, why adding this test case is important?

**Comment by nikamirrr** [comment]
Because the generated scales need to be in the closed loop.
Meaning the last step needs to wrap the scale from the last note to the first.
In the current test codes the last step is simply ignored.
Alternatively one may change the exercise and require that an extra note is generated at the end and matches the first note.

**Comment by m-a-ge** [comment]
@nikamirrr, thanks for the explanation, I'm starting understanding the issue.
Give me some time to check a few things before proceeding with the merge

**Comment by m-a-ge** [comment]
@nikamirrr, thank you for working on this :hammer_and_wrench:

**Pull request merged**
