### PR TITLE
Reduced Practices Arrays to 8 Exercise References per concept.

### PR DESCRIPTION
**Pull request by BethanyG**
...or at least I hope I did.  Once more, with feeling.

### CODE REVIEW

**Review by SleeplessByte — APPROVED** [review]
Looks good. Want me to run a script to figure out if it's right now? Or do you just want to merge and see if it works?

**Comment by BethanyG** [comment]
@SleeplessByte  - Just seeing this.  Thanks for the offer, I think there shouldn't be more than 8 exercises referenced for each concept now - so I am just going to go for it.  If there are still some broken, they'd be off by ... _maybe_ one, so I think we're good.

**Comment by BethanyG** [comment]
Linking to the original PR for this, so that we don't loose that description/info:  [PR #2377](https://github.com/exercism/python/pull/2377)

**Comment by BethanyG** [comment]
...aaaand of course that was a lie.  Will do a small follow-on PR to clean up the `numbers` and `string` references, which it looks like I missed.

**Pull request merged**
