### PR TITLE
Synced `instructions.md` & `introduction.md` Files from Problem Specifications

### PR DESCRIPTION
**Pull request by BethanyG**
Synced the `introduction.md` and `instruction.md` files for the following exercises:

- [x] accumulate
- [x] binary
- [x] binary-search
- [x] book-store
- [x] bowling
- [x] darts
- [x] error-handling
- [x] gigasecond
- [x] hexadecimal
- [x] killer-sudoku-helper
- [x] linked-list
- [x] nucleotide-count
- [x] octal
- [x] pangram
- [x] parallel-letter-frequency
- [x] queen-attack
- [x] roman-numerals
- [x] saddle-points
- [x] secret-handshake
- [x] sieve
- [x] strain
- [x] sum-of-multiples
- [x] trinary
- [x] two-fer

### CODE REVIEW

**Comment by ErikSchierboom** [comment]
I'm holding off on approving as this will have the same issue mentioned in https://github.com/exercism/python/pull/3373#issuecomment-1542318581

**Comment by BethanyG** [comment]
It will?!!?  AFAK, none of these include re-generated test files -- these are all problem descriptions and  introductions which shouldn't trigger any re-submissions.

**Comment by BethanyG** [comment]
I'll put a hold label on this, though.  😄

**Comment by ErikSchierboom** [comment]
@BethanyG I'll double check when I have some time!

**Comment by ErikSchierboom** [comment]
@BethanyG I'm sorry, but I am totally swamped by getting everything related to payments and Exercism Premium done.

**Comment by ErikSchierboom** [comment]
giphy

**Comment by iHiD** [comment]
> It will?!!? AFAK, none of these include re-generated test files -- these are all problem descriptions and introductions which shouldn't trigger any re-submissions, unless I am misunderstanding things.


To be clear, until these latest changes docs **would** trigger reruns as they're included in the important files, which are what we use as our flag (ie they tell students they need to update). However, we've now refined the logic so it doesn't include docs.

**Comment by BethanyG** [comment]
Wow.  Thank you **thank you both** for all the work put in to fix and test this!!  
I will never look at something as "just a sync" again!  🙀 

❤️ 🧡 💛 💚 💙 💜

**Pull request merged**
