### PR TITLE
Mark self as alumnus maintainer

### PR DESCRIPTION
**Pull request by cmccandless**

### CODE REVIEW

**Comment by cmccandless** [comment]
Cool bot, that's new

**Comment by cmccandless** [comment]
I no longer have merge permissions here, so whoever approves this PR should go ahead and merge it too.

**Comment by angelikatyborska** [comment]
@cmccandless This file is no longer used for anything (and might get deleted soon), so you didn't really need to worry about it 🙂

**Comment by cmccandless** [comment]
Wasn't sure; I'm still getting notifications for this repo and I'm trying
to eliminate possible causes. Thanks.

**Comment by BethanyG** [comment]
On the chance it will help, I will approve and merge.  😄

**Review by BethanyG — APPROVED** [review]

**Comment by ErikSchierboom** [comment]
This file is indeed no longer used. I'll do a bulk PR across tracks to remove the file.

**Comment by J08K** [comment]
`maintainers.json` has been removed, therefore I will be closing this PR. Thanks everyone!

**Pull request closed without merging**
