### PR TITLE
(WIP) Implement exercise bowling

### PR DESCRIPTION
**Pull request by splashofcrimson**

### CODE REVIEW

**Comment by Average-user** [comment]
it's just me, or there are no changes?

**Comment by m-a-ge** [comment]
@Average-user I believe this PR is meant to claim an implementation of this exercise

**Comment by Average-user** [comment]
@m-a-ge Ups. I could make one, but i've never liked the bowling kata.

**Comment by m-a-ge** [comment]
@splashofcrimson are you still interested in implementing this one?

**Comment by splashofcrimson** [comment]
Sorry, please ignore this - I'm new to git

**Comment by m-a-ge** [comment]
@splashofcrimson do you mean that you don't want to implement the exercise? 
If so, please close the PR to show that other people can start working on this

**Pull request closed without merging**
