### PR TITLE
bracket-push: update tests to v1.5.0

### LINKED ISSUE #1583: bracket-push: update tests to v1.5.0
The [test suite](https://github.com/exercism/python/blob/master/exercises/bracket-push/bracket_push_test.py) for bracket-push is out of date and needs updated to conform to the [latest canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/bracket-push/canonical-data.json).

### PR DESCRIPTION
**Pull request by Nishant23**
Closes #1583

### CODE REVIEW

**Comment by cmccandless** [comment]
You've address 1 of my 3 comments. Please fix the other 2.

**Comment by Nishant23** [comment]
> You've address 1 of my 3 comments. Please fix the other 2.

I have updates the PR name as per the given format. I've also updated canonical data version referenced in the test suite comment. 
I am a little bit confused with respect to magic word on how to use it.

**Comment by cmccandless** [comment]
Confusion is OK; part of the process of contributing to open source is learning.

"Magic words" automatically link an issue to a PR, closing that issue when the PR is merged. To use them, just put "Closes #<issue number>" in the description of the PR (not in a comment, or it won't work).

**Comment by cmccandless** [comment]
Merged; thanks for working on this!

**Pull request merged**
