### PR TITLE
Make probot/stale more useful

### PR DESCRIPTION
**Pull request by cmccandless**
Propose the following changes:
- `daysUntilStale: 60 -> 21`: With 5 track maintainers (3+ active), issues are being manually closed after ~20 days frequently. 60 days is too long.
- Add `epic` to `exemptLabels`: `epic` denotes issues that are usually super-issues, and closing every sub-issue takes a lot of effort and time.
- `staleLabel: on hiatus -> abandoned`: `abandoned` is typically used by the maintainers here, so change for consistency

### CODE REVIEW

**Comment by cmccandless** [comment]
@behrtam @N-Parsons any objections?

**Comment by N-Parsons** [comment]
My only concern would be that some sub-issues of large ones could end up getting closed. The `epic` label would protect the main one, but the exercise-specific issues would still be vulnerable.

Perhaps we should also add the `beginner friendly` label to the exemption? These are good issues for new people, and I don't think it matters if they stay around longer than 21 days. I think `enhancement` might also be a good one to exclude? If we've tagged it as an enhancement, we've recognised it's value as something that should be changed, but sometimes that doesn't mean that it will be easily resolvable or resolved quickly.

Alternatively, we need another label (could be one that we have already) that we can add to things that just need doing, regardless of how long it sits there?

**Comment by cmccandless** [comment]
@N-Parsons Apologies for the late response on this; somehow the notification must've slipped between the cracks. 

>Perhaps we should also add the `beginner friendly` label to the exemption? These are good issues for new people, and I don't think it matters if they stay around longer than 21 days. 

I agree with your reasoning.

>I think enhancement might also be a good one to exclude? If we've tagged it as an enhancement, we've recognised it's value as something that should be changed, but sometimes that doesn't mean that it will be easily resolvable or resolved quickly.

Fair enough.

>Alternatively, we need another label (could be one that we have already) that we can add to things that just need doing, regardless of how long it sits there?

We already have `pinned` for this.

**Comment by N-Parsons** [comment]
@cmccandless, no worries - I've been busy myself recently and lost track of a lot of stuff.

If you're happy to add those things, then I guess I'm happy to approve the changes.

**Comment by cmccandless** [comment]
@N-Parsons done.

**Comment by N-Parsons** [comment]
I feel like there's a consensus here, so I've merged it. Thanks @cmccandless!

**Pull request merged**
