### PR TITLE
grains: Update tests to match canonical-data 

### LINKED ISSUE #996: grains: check test version and update if necessary
As identified in #784, some of the tests currently don't reference the version number for the `canonical-data.json` that they are based on, `grains` is one of them. In order to help with the ongoing maintenance of this track, we're in the process of checking the tests against the current version of the `canonical-data.json` - if they are up-to-date, then you can just add the version string, but if they are out-of-date, then the tests will need updating.

Tests should typically be ordered according to their order in the canonical data, since this makes it easier to check and update them in future. If you think that there's a better order, please let us know your reasoning in your PR.

If there are some additional tests that currently exist in this track but which aren't in the canonical data, these can be kept if you think that they are useful. They should be placed at the bottom of the test cases, and it would also be super-helpful if you could add a comment before them saying `# Additional tests for this track` to make it clear that they aren't part of the canonical data.

The version string should be placed just before the first test class and followed by a blank line. For this exercise, the version string is:
```
# Tests adapted from `problem-specifications//canonical-data.json` @ v1.0.0
```

**Test suite:** [exercism/python/exercises/grains/grains_test.py](https://github.com/exercism/python/blob/master/exercises/grains/grains_test.py)
**Canonical data:** [exercism/problem-specifications/exercises/grains/canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/grains/canonical-data.json)

### PR DESCRIPTION
**Pull request by denislooby**
Resolves #996 

Removes multiple total_after tests in favor of one at the end as specified in canonical-data.

### CODE REVIEW

**Comment by cmccandless** [comment]
@denislooby Thanks for you pull request!

I'm not sure that removing the extra `total_after` calls is fully necessary. In particular, I think the calls inside the exception tests should probably remain, since there is no guarantee that `total_after` calls `square` (therefore invoking the same validation tests).

@N-Parsons thoughts?

**Comment by denislooby** [comment]
Yes, I was wondering about that.
The canonical-data and the test seems to have had different interpretations of the readme.
```
Write code that shows:
- how many grains were on each square, and
- the total number of grains
```
But you could argue for both ways.

**Comment by denislooby** [comment]
Should there be a 1-1 mapping between test asserts and cases in the canonical-data or is it less rigid than that?

**Comment by cmccandless** [comment]
@denislooby There's nothing wrong with multiple assertions in the same test case (for example: [kindergarten-garden does this](https://github.com/exercism/python/blob/7a2904e9614dff06e449a02c800145fccab6d049/exercises/kindergarten-garden/kindergarten_garden_test.py)).

**Comment by denislooby** [comment]
@cmccandless I know multiple asserts in a test are ok, but should the canonical-data reflect all of them?
In kindergarten-garden it does seem to have them all in the json.

**Comment by cmccandless** [comment]
@denislooby as long as the additional asserts are neither redundant nor contradictory to the canonical ones, I would say that they are fine.

**Comment by denislooby** [comment]
@cmccandless Ok good to know. In that case definitely the exception test cases should be added back.
I'd be happy to add back the others too if you fell it would be for the best.

**Comment by cmccandless** [comment]
@denislooby I think simply restoring the exception test cases should be enough.

**Comment by N-Parsons** [comment]
@denislooby, thanks for your work on this.

(This comment got long, so TL;DR: I'm happy to merge once you've added the exception tests back)

I think that at the very least we should keep the exception tests for `total_after` - lots of implementations won't have the two functions connected, since there are mathematical tricks to jump straight to the answer, so testing for exception handling in both functions will be important.

Adding back the other tests would mean that the functions are being tested more, which would normally be considered a good thing, but realistically, testing one valid value and 3 exceptional values should be sufficient to fully test implementations of `total_after`. (In other languages these may be important/useful, but Python has no integer overflow). The aim of `total_after` is to know how many grains of rice are owed in total, so just testing square `64` seems fine to me.

**Comment by denislooby** [comment]
@N-Parsons Changes done

**Comment by N-Parsons** [comment]
Thanks @denislooby! Sorry it took a while for me to get back to this.

**Pull request merged**
