### PR TITLE
flatten-array: update tests to v1.1.0

### LINKED ISSUE #995: flatten-array: check test version and update if necessary
As identified in #784, some of the tests currently don't reference the version number for the `canonical-data.json` that they are based on, `flatten-array` is one of them. In order to help with the ongoing maintenance of this track, we're in the process of checking the tests against the current version of the `canonical-data.json` - if they are up-to-date, then you can just add the version string, but if they are out-of-date, then the tests will need updating.

Tests should typically be ordered according to their order in the canonical data, since this makes it easier to check and update them in future. If you think that there's a better order, please let us know your reasoning in your PR.

If there are some additional tests that currently exist in this track but which aren't in the canonical data, these can be kept if you think that they are useful. They should be placed at the bottom of the test cases, and it would also be super-helpful if you could add a comment before them saying `# Additional tests for this track` to make it clear that they aren't part of the canonical data.

The version string should be placed just before the first test class and followed by a blank line. For this exercise, the version string is:
```
# Tests adapted from `problem-specifications//canonical-data.json` @ v1.1.0
```

**Test suite:** [exercism/python/exercises/flatten-array/flatten_array_test.py](https://github.com/exercism/python/blob/master/exercises/flatten-array/flatten_array_test.py)
**Canonical data:** [exercism/problem-specifications/exercises/flatten-array/canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/flatten-array/canonical-data.json)

### PR DESCRIPTION
**Pull request by AiryShift**
Old tests that aren't part of v1.1.0 were moved to the end
Resolves #995

### CODE REVIEW

**Comment by AiryShift** [comment]
Resolves #995

**Comment by cmccandless** [comment]
@AiryShift Thanks for your pull request! [Magic words](https://help.github.com/articles/closing-issues-using-keywords/) only work in included in the PR description, not in comments. Please edit the description to include "Resolves #995".

**Comment by AiryShift** [comment]
Apologies for not doing that earlier. Should be fixed now,

**Comment by m-a-ge** [comment]
@AiryShift there is a style issue in your changes:
```text
2.83s$ flake8
./exercises/flatten-array/flatten_array_test.py:7:1: E302 expected 2 blank lines, found 1

The command "flake8" failed and exited with 1 during .
Your build has been stopped.
```

**Comment by N-Parsons** [comment]
Thanks @AiryShift!

**Pull request merged**
