### PR TITLE
[Della's Delays at the DMV]: New Concept Exercise

### PR DESCRIPTION
**Pull request by bobahop**

### CODE REVIEW

**Comment by bobahop** [comment]
Did some stubs of functions and tests just to try to make the test errors go away, but no joy. Real functions and tests will most likely be different (and there will be more functions and tasks.)

**Comment by bobahop** [comment]
Perhaps the exemplar needs to be implemented for the test errors to go away?

**Comment by bobahop** [comment]
Yup, that was it. Well, I just wanted to get the file structure set up. Will think over the weekend about the story and all that...

**Comment by BethanyG** [comment]
I'm going to close this for now, since it's been open since June without movement.  We can always reopen when work resumes.

**Pull request closed without merging**
