### PR TITLE
secret-handshake: add test template

### LINKED ISSUE #1988: secret-handshake: add test template
## Task
Create a test template file for `secret-handshake`

### Details
1. If this is your first time contributing to this repository, welcome!
    - Contributing to a repository on GitHub requires a [fork](https://help.github.com/en/articles/fork-a-repo)
1. Create a branch on your local repository called `secret-handshake-add-test-template`
    - Run: `git checkout -b secret-handshake-add-test-template`
1. Clone problem-specifications repository; this is used to populate the template
    - Run: `git clone https://github.com/exercism/problem-specifications ../problem-specifications`
1. Create `exercises/secret-handshake/.meta/template.j2`
    - See [Generator Documentation] for more information
1. Generate test file from new template
    - Run: `bin/generate_tests.py secret-handshake`

At this point, if the generator fails, or you are otherwise stuck,
please feel free to reach out! It is perfectly acceptable to submit
an incomplete PR in order to get feedback or assistance.

### Resources
- [Contributing Guide]
- [Generator Documentation]
- [Closing issues using keywords]

[Contributing Guide]: https://github.com/exercism/python/blob/master/docs/CONTRIBUTING.md
[Generator Documentation]: https://github.com/exercism/python/blob/master/docs/GENERATOR.md
[Closing issues using keywords]: https://help.github.com/en/articles/closing-issues-using-keywords

### PR DESCRIPTION
**Pull request by crsmi**
Resolves #1988 '

I tried to make the template flexible around the additional tests, but am not sure how well I succeeded.

### CODE REVIEW

**Comment by yawpitch** [comment]
@cmccandless do you know the rationale for the extra-credit tests and the **secret_code** function?

Seems to me there are numerous cases in which the **secret_code** in the example.py would fail, since it's ignoring invalid actions in the input and it's assuming that the input is fully reversed if only the first two items are.

If round-tripping from code to commands and back _is_ something we want in this exercise, maybe that should be stated in the canonical-data? Or maybe we should remove these from "extra-credit" and make them mandatory?

As is this exercise is unusual because there's a slug in the secret_handshake.py file for a function that will _never_ be called if the student doesn't manually enable the skipped tests, and because the extra-credits functionality is never mentioned anywhere in the problem description.

Maybe we should just remove it and simplify our lives?

**Comment by cmccandless** [comment]
Huh. TIL about the `~` operator in Jinja templates.

@yawpitch I'm in favor of removing the additional tests. The property they test is not terribly well defined, and is not canonical, so it seems out-of-scope.

**Comment by yawpitch** [comment]
> @yawpitch I'm in favor of removing the additional tests. The property they test is not terribly well defined, and is not canonical, so it seems out-of-scope.

Agreed. Removing it should considerably simplify the template and this PR.

**Comment by crsmi** [comment]
Sorry, I messed up the git flow there a little bit. I think I fixed it along with the removal of the additional tests.

**Comment by yawpitch** [comment]
Since the test for **secret_code** has now been removed the `def secret_code` block in both the example.py and secret_handshake.py should also be removed. That will also remove the need for importing that function in the secret_handshake_tests.py.

**Comment by crsmi** [comment]
Alright, **secret_code** removed.

**Pull request merged**
