### PR TITLE
[Gigasecond]: Large Number Formatting Instruction Append and Hints File

### PR DESCRIPTION
**Pull request by AndrewLawendy**

### CODE REVIEW

**Comment by BethanyG** [comment]
Hi @AndrewLawendy 👋🏽 

Thank you for submitting this PR!  While the information on number formatting is super-useful for students, this advice seems better suited to a [hints](https://github.com/exercism/docs/blob/main/building/tracks/practice-exercises.md#file-docshintsmd) file rather than an _approach_.

[Approaches](https://exercism.org/docs/building/tracks/approaches) tend to walk students through a particular solution or set of solutions, pointing out strategies and details for an exercise.  They might even compare or contrast  different techniques for completing the exercise.  For an example, see this approaches doc for [pangram](https://exercism.org/tracks/python/exercises/pangram/dig_deeper).

Currently as written, your PR goes over number formatting, but doesn't talk to the student about uses of `datetime` -- or how to solve the problem with `timedelta` or other techniques.  Do you plan to add a fuller explanation of a solution or technique?  If not, I would recommend adding this information to the [instruction append](https://github.com/exercism/python/blob/main/exercises/practice/gigasecond/.docs/instructions.append.md) for the exercise or its [hints](https://github.com/exercism/python/blob/main/exercises/practice/gigasecond/.docs/hints.md) file instead.

Please also note that we use reflinks in our markdown documents rather than in-line links.  For more information, please see our [Markdown Specification](https://exercism.org/docs/building/markdown/markdown) docs.

Thanks again for your work on this.

**Review by BethanyG — CHANGES_REQUESTED** [review]
Please see my earlier note.  Thanks!

**Comment by AndrewLawendy** [comment]
@BethanyG I understand and I agree with you
One thing to debate over
Hints don't show on the platform, only in the downloaded files

Do you think it's better to be put in the instructions or really keep it in hint?

**Comment by BethanyG** [comment]
Hints actually do show on the platform, but accessing them is non-intuitive for new users:

image

once the 💡 is clicked, a modal pops up with the hints:

image


As for placement, it doesn't really hurt anything to put the information in _both_  the append and the hints.  That way, we have two chances to express it to the student.  😄  Each would have a different form.  Hints tend to be less direct and more, well _hinty_ 😉 .

Also -- be warned that if you open a different PR for `hints` & `appends`, the bot will likely close it.  Don't worry tho -- I will see it and re-open it if that happens.

**Comment by AndrewLawendy** [comment]
Ooh, I've been using Exercism for years and didn't know about that 😂
I'll add it in both

**Comment by AndrewLawendy** [comment]
@BethanyG I made the change, but I don't understand the change request?

**Comment by BethanyG** [comment]
Oh - sincere apologies, @AndrewLawendy  -- I haven't yet reviewed your changes, so the change request is still in place from last time.  I'll make sure to review this by EOD my time (_I am in the PDT timezone_).

**Comment by AndrewLawendy** [comment]
No need 😊
Thanks for your reply

**Review by BethanyG — APPROVED** [review]
Hi @AndrewLawendy  - Thanks so much for this PR!  Apologies again for the delay in getting things reviewed.  Rather than put you through another edit cycle, I went ahead and reformatted the two files a bit.  

[Hints](https://github.com/exercism/docs/blob/main/building/tracks/practice-exercises.md#file-docshintsmd) have a particular requirement to be bulleted or they won't come up correctly in the UI, so I attempted to do that for the `hints.md` file.  [Instruction appends](https://github.com/exercism/docs/blob/main/building/tracks/practice-exercises.md#file-docsinstructionsappendmd) are tagged onto the end of the instructions, so I massaged things a bit there as well.

Please let me know if these edits look OK to you.  If so, I will merge them to the site.  If not -- please feel free to make changes (_although the hints need to stay in a bulleted list_).

**Comment by AndrewLawendy** [comment]
@BethanyG LGTM
Feel free to merge whenever you want

**Comment by AndrewLawendy** [comment]
@BethanyG Thanks 
See you on the next pr ✌️

**Pull request merged**
