### PR TITLE
[Comparisons] Corrected typo

### PR DESCRIPTION
**Pull request by Timo4B**
changed "True or False" to "'True' or 'False'" as in the other texts #2906

### CODE REVIEW

**Comment by BethanyG** [comment]
@Timo4B  - why did you close this PR?

**Comment by Timo4B** [comment]
Sorry I mixed it up. I thought it would be one of these PRs that were not welcome. I'll reopen it.

**Comment by Timo4B** [comment]
I think it was this message: "Some checks were not successful". I thought I did something wrong.

**Comment by BethanyG** [comment]
Nope!  Which is why I didn't comment.  This failure is actually related to something I need to clean up.  The problem specifications for some practice exercises changed, and I have to test them and re-generate files.  Nothing will pass CI until I do that.  But rather than clutter your PR with it, I will submit a new PR.  😄   It may take a while to get it reviewed, but once that is in, your two PRs will then pass CI, and can be merged.  Apologies for the delay on that.

**Comment by Timo4B** [comment]
Thank you for the explanation!
If I feel more small fixes are needed, I will make them in the same way with Issue and Pull Request. I hope that it helps.

**Review by BethanyG — APPROVED** [review]
Thank you for this!  🌟

**Pull request merged**
