### PR TITLE
high-scores: update test suite to v4.0.0 (closes #1672)

### LINKED ISSUE #1672: high-scores: update tests to v4.0.0
The [test suite](https://github.com/exercism/python/blob/master/exercises/high-scores/high_scores_test.py) for high-scores is out of date and needs updated to conform to the [latest canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/high-scores/canonical-data.json).

### PR DESCRIPTION
**Pull request by gabriel376**
Update exercise high-scores to v4.0.0 (closes #1672)

[Problem Specification](https://github.com/exercism/problem-specifications/tree/master/exercises/high-scores)

**Changes**:
1. Removed **report** part from **README**
2. Renamed function **personal_top()** to **personal_top_three()** on **example.py** and **high_scores_test.py**
3. Removed **deprecated** test cases from **high_scores_test.py** according to problem specification
4. Removed function **report()** on **example.py**
5. Updated test version header to **v4.0.0** on **high_scores_test.py**

### CODE REVIEW

**Comment by gabriel376** [comment]
> Looking good! Just one minor thing: I see you've attempted to link this PR to #1672, and that's great! There is actually an official way to do this: check out [magic words](https://help.github.com/articles/closing-issues-using-keywords/).
> 
> Please use that to link the issue, and we should be good to go!

I updated title and description to use keyword **closes**
Do I have to update commit message too ?
Thank you!

**Comment by cmccandless** [comment]
> I updated title and description to use keyword **closes**

It does no harm, but for future reference, only the description requires the keyword

> Do I have to update commit message too ?

Nope, just the description. :+1:

**Comment by cmccandless** [comment]
Merged; thanks for working on this!

**Comment by gabriel376** [comment]
Thank you!

**Pull request merged**
