### PR TITLE
Implement exercise passio

### LINKED ISSUE #751: paasio: implement exercise
There are exercises that are not yet implemented in Python track (the full list of them - https://github.com/exercism/python/issues/417#issuecomment-334841778).
You can help us change this situation by implementing this one. Ref #417

The guide ["Implement an exercise from specification"](https://github.com/exercism/docs/blob/master/you-can-help/implement-an-exercise-from-specification.md) will help you succeed.

If you still have questions, I encourage you to ask them before starting working on the issue.

I also suggest claiming the issue by creating an empty PR as stated [here](https://github.com/exercism/docs/blob/master/you-can-help/implement-an-exercise-from-specification.md#avoiding-duplicate-work)

Please note that there are some special ['closing issue' keywords](https://help.github.com/articles/closing-issues-using-keywords/) that you can put in description of your PR and Github will take care of closing the corresponding issue automatically after merge.
This simple thing helps us a lot, and makes our life a bit easier

### PR DESCRIPTION
**Pull request by rohitrango**
Fixes #751.
Work in progress.

### CODE REVIEW

**Comment by rohitrango** [comment]
@m-a-ge I had a look at the description and the Wikipedia page. But I'm not getting a clear idea as to what is expected from the problem. Do I have to implement a ReadWrite interface for a buffer?

**Comment by cmccandless** [comment]
@rohitrango Try looking at the [Go implementation](/exercism/go/tree/master/exercises/paasio) and see if that helps clarify your questions.

**Comment by cmccandless** [comment]
@rohitrango are you still working on this?

**Comment by rohitrango** [comment]
I'm sorry, but I lost track. I think I'll work on some other issue as of now.

**Pull request closed without merging**
