### PR TITLE
The `secrets` concept

### PR DESCRIPTION
**Pull request by colinleach**
A teeny, tiny concept. I wish they were all this quick to put together.

### CODE REVIEW

**Comment by BethanyG** [comment]
[random vs pseudo-random](https://www.khanacademy.org/computing/computer-science/cryptography/crypt/v/random-vs-pseudorandom-number-generators)  too much?  Or would this be a good link?

**Comment by BethanyG** [comment]
That being said, [wikipedia](https://en.wikipedia.org/wiki/Pseudorandomness) has an easily scannable and understandable text version as well.

**Comment by colinleach** [comment]
The Wikipedia entry certainly looks worth including. Maybe Khan Academy as well?

To do it properly, there is Knuth, Chapter 3. We might get into trouble for adding that.

**Comment by BethanyG** [comment]
Alrighty.  I did the edits via [GitHub Desktop](https://desktop.github.com/) this time, rather than the web interface.  Seemed quicker.  But I am also happy to do it via the web interface, if you prefer.  I'll probably do that for longer ones, or in cases where there is discussion to be had/lots of suggestions to be made.

If all this looks good, I can merge this down.  Just let me know. 😄

**Comment by BethanyG** [comment]
> _To do it properly, there is Knuth, Chapter 3. We might get into trouble for adding that._

🤣 

Do. Not. Tempt me!  .... _oooh, I so want to ... but the blowback t'would be **fierce**_

**Comment by BethanyG** [comment]
**BTW**:  This `[concept:python/random]()` formulation is a [widget](https://github.com/exercism/docs/blob/main/building/markdown/widgets.md), used for when we refer back to a concept or exercise.  I don't remember to use them, but we should do so as we build out the tree more.

**Comment by colinleach** [comment]
Looks good to me, merge when you're ready.

I'd been meaning to get my head around Exercism widgets, so this is a timely prompt.

**Comment by colinleach** [comment]
I've not used GitHub Desktop recently. Mostly, I use GitKraken (on Linux and Windows), though not to anywhere near its full potential. I really must read the documentation sometime (after all, I'm paying for the Pro version).

**Review by BethanyG — APPROVED** [review]
Woot!  One more off the list!  💥 🌟 🚀 

Thank you for this.  😄

**Comment by colinleach** [comment]
To repeat: I wish it was always this easy!

**Pull request merged**
