### PR TITLE
add new exercise: armstrong-numbers (closes  #1131)

### LINKED ISSUE #1131: Armstrong-number: implement new exercise
Problem-specifications introduces a new exercise called ["armstrong-numbers"](https://github.com/exercism/problem-specifications/tree/master/exercises/armstrong-numbers).
The goal of this issue would be to implement it in the python track.

### PR DESCRIPTION
**Pull request by pheanex**
How is this for a first try?

### CODE REVIEW

**Comment by cmccandless** [comment]
@pheanex Merged. Thanks for working on this!

**Comment by pheanex** [comment]
*Yay* thank you :tada: :smile:

**Comment by pheanex** [comment]
btw @cmccandless can i do anything else to help get this on the website?

**Comment by cmccandless** [comment]
@pheanex It is my understanding that Exercism.io will automatically add new exercises as they are defined in `config.json`. I am not sure how often it rescans, as there are many tracks it must check. I *think* it should be available for fetching (`exercism f python armstrong-numbers`) within 24hrs.

**Comment by pheanex** [comment]
ok, cool. Thank you for the info @cmccandless :smile:

**Pull request merged**
