### PR TITLE
docs: Fixed a missing word in pangram instructions

### PR DESCRIPTION
**Pull request by mael-queau**
> The quick brown fox jumps over the lazy ***blue*** dog

It's not much, but I thought I'd propose to add it back!

### CODE REVIEW

**Comment by BethanyG** [comment]
Hi @mael-queau 👋🏽 

Thank you so much for submitting this PR!  

Since `pangram` is a practice exercise that is pulled from a common [problem-specifications](https://github.com/exercism/problem-specifications) repo, we ask that you propose the change there, so that all programming language tracks can take advantage of it.  _Many thanks!_ 💛 💙 🌈

**Comment by IsaacG** [comment]
@mael-queau  Out of curiosity, why should "blue" be included in that sentence? It's not present in the [Wikipedia article](https://en.wikipedia.org/wiki/The_quick_brown_fox_jumps_over_the_lazy_dog).

**Comment by mael-queau** [comment]
Well, now that you mention it, I should've double-checked... I learnt it that way, and I could have sworn the word "blue" was in it, but clearly I was mistaken. Since I don't believe in the Mandela Effect, I guess I'm just senile! 😅
Thanks for pointing it out 🙂

**Comment by BethanyG** [comment]
@mael-queau  - I  didn't even think about it ... **b** is covered by "brown"  😄   Closing.

**Pull request closed without merging**
