### PR TITLE
rna-transcription: update tests to version 1.0.1

### LINKED ISSUE #1020: rna-transcription: update tests to version 1.0.1
As identified in #784, some of the exercise test-suites are out-of-date, `rna-transcription` is one of them. It would therefore be really helpful for people to go through and update the test suite to match the canonical data.

Tests should typically be ordered according to their order in the canonical data, since this makes it easier to check and update them in future. If you think that there's a better order, please let us know your reasoning in your PR.

If there are some additional tests that currently exist in this track but which aren't in the canonical data, these can be kept if you think that they are useful. They should be placed at the bottom of the test cases, and it would also be super-helpful if you could add a comment before them saying `# Additional tests for this track` to make it clear that they aren't part of the canonical data.

The version string should be placed just before the first test class and followed by a blank line. For this exercise, the version string is:
```
# Tests adapted from `problem-specifications//canonical-data.json` @ v1.0.1
```

**Test suite:** [exercism/python/exercises/rna-transcription/rna_transcription_test.py](https://github.com/exercism/python/blob/master/exercises/rna-transcription/rna_transcription_test.py)
**Canonical data:** [exercism/problem-specifications/exercises/rna-transcription/canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/rna-transcription/canonical-data.json)

### PR DESCRIPTION
**Pull request by kishan3**
Resolves #1020

### CODE REVIEW

**Comment by m-a-ge** [comment]
Build failed due to code style issues:
```text
3.15s$ flake8
./exercises/pangram/pangram_test.py:7:1: E302 expected 2 blank lines, found 1
./exercises/pangram/pangram_test.py:8:1: W293 blank line contains whitespace
./exercises/pangram/pangram_test.py:14:1: W293 blank line contains whitespace
./exercises/pangram/pangram_test.py:27:80: E501 line too long (82 > 79 characters)
./exercises/pangram/pangram_test.py:28:1: W293 blank line contains whitespace
./exercises/pangram/pangram_test.py:53:1: W293 blank line contains whitespace
./exercises/pangram/pangram_test.py:54:5: E265 block comment should start with '# '
./exercises/pangram/pangram_test.py:55:1: W293 blank line contains whitespace
./exercises/pangram/pangram_test.py:61:1: E305 expected 2 blank lines after class or function definition, found 1
./exercises/pangram/pangram_test.py:61:11: E999 SyntaxError: invalid syntax
./exercises/pig-latin/pig_latin_test.py:29:80: E501 line too long (82 > 79 characters)
./exercises/pig-latin/pig_latin_test.py:43:1: W293 blank line contains whitespace
./exercises/pig-latin/pig_latin_test.py:63:1: W293 blank line contains whitespace
./exercises/pig-latin/pig_latin_test.py:82:1: W293 blank line contains whitespace
./exercises/pig-latin/pig_latin_test.py:90:1: E305 expected 2 blank lines after class or function definition, found 1
The command "flake8" failed and exited with 1 during .
```

**Comment by cmccandless** [comment]
To quote @N-Parsons in #1030:
> Please use a meaningful title for the PR that includes the exercise name - it makes it much easier to handle pull requests. I would suggest using all-your-base: Update test order and version string". Could you also please add the [magic words](https://help.github.com/articles/closing-issues-using-keywords/) `resolves #1014` to your PR description so that merging list PR closes the corresponding issue.

In your case, the corresponding issue is #1020

**Comment by kishan3** [comment]
Fixed styling issues.

**Comment by m-a-ge** [comment]
Thanks, @kishan3

**Pull request merged**
