### PR TITLE
[Exercise Instructions, Intros, Metadata] Sync to problem specs

### PR DESCRIPTION
**Pull request by BethanyG**
Used `configlet 4.0.0-beta.10` to sync exercises to problem specifications.  

This seems like a pretty large list, so I am not sure if something went wrong, or there are very small changes that were picked up by configlet that weren't there last month.

**edited to add** -- the bulk of these look like one sentence per line edits and other small tidyings.

`.docs` changes:

- 	modified:   exercises/practice/accumulate/.docs/instructions.md
- 	modified:   exercises/practice/binary-search/.docs/instructions.md
- 	modified:   exercises/practice/binary/.docs/instructions.md
- 	modified:   exercises/practice/bowling/.docs/instructions.md
- 	modified:   exercises/practice/darts/.docs/instructions.md
- 	modified:   exercises/practice/error-handling/.docs/instructions.md
- 	modified:   exercises/practice/gigasecond/.docs/introduction.md
- 	modified:   exercises/practice/hexadecimal/.docs/instructions.md
- 	modified:   exercises/practice/killer-sudoku-helper/.docs/instructions.md
- 	modified:   exercises/practice/largest-series-product/.docs/instructions.md
- 	**`new file`**:   exercises/practice/largest-series-product/.docs/introduction.md
- 	modified:   exercises/practice/linked-list/.docs/instructions.md
- 	modified:   exercises/practice/nucleotide-count/.docs/instructions.md
- 	modified:   exercises/practice/octal/.docs/instructions.md
- 	modified:   exercises/practice/pangram/.docs/instructions.md
- 	modified:   exercises/practice/pangram/.docs/introduction.md
- 	modified:   exercises/practice/parallel-letter-frequency/.docs/instructions.md
- 	modified:   exercises/practice/rna-transcription/.docs/instructions.md
- 	**`new file`**:   exercises/practice/rna-transcription/.docs/introduction.md
- 	modified:   exercises/practice/saddle-points/.docs/instructions.md
- 	**`new file`**:   exercises/practice/saddle-points/.docs/introduction.md
- 	modified:   exercises/practice/secret-handshake/.docs/instructions.md
- 	modified:   exercises/practice/sieve/.docs/instructions.md
- 	modified:   exercises/practice/strain/.docs/instructions.md
- 	modified:   exercises/practice/sum-of-multiples/.docs/instructions.md
- 	**`new file`**:   exercises/practice/sum-of-multiples/.docs/introduction.md
- 	modified:   exercises/practice/trinary/.docs/instructions.md
- 	modified:   exercises/practice/two-fer/.docs/instructions.md

`metadata` changes:

- modified:   exercises/practice/binary/.meta/config.json
- modified:   exercises/practice/etl/.meta/config.json
- modified:   exercises/practice/hexadecimal/.meta/config.json
- modified:   exercises/practice/nucleotide-count/.meta/config.json
- modified:   exercises/practice/octal/.meta/config.json
- modified:   exercises/practice/point-mutations/.meta/config.json
- modified:   exercises/practice/trinary/.meta/config.json

### CODE REVIEW

**Comment by MatthijsBlom** [comment]
Should maybe wait for exercism/problem-specifications#2261 to get merged.

**Comment by MatthijsBlom** [comment]
I am confused. The diff suggests that e.g. the _Sum of Multiples_ instructions will be replaced, however it seems that [they already have been](https://github.com/exercism/python/blob/869f0723275a2f7e32b89e05d9baf150f40b2275/exercises/practice/sum-of-multiples/.docs/instructions.md).

**Comment by MatthijsBlom** [comment]
What, then, does the diff mean? I thought it was comparing both branches' heads, but now it seems it actually isn't.

**Comment by BethanyG** [comment]
Actually, I am going to close this for now.  The velocity of change has picked up, and it is probably easier to wait for a slowdown and then re-run configlet to pick up any 'hanging' changes.  I was primarily doing this to work on `Bank Account`, now that there is canonical data -- but I can do that as a stand-alone.

**Comment by MatthijsBlom** [comment]
@ee7 Sorry, I didn't see your comment until now. I think I get it now, thanks.

@BethanyG [people are getting confused](https://forum.exercism.org/t/julia-exercise-sum-of-multiples-instructions-incorrect/5270) by the currently slightly outdated Sum of Multiples instructions. On the plus side, the patch storm around that exercise has subsided. Shall we reopen this PR, or shall I send (a custom) one myself, or&hellip;?

**Pull request closed without merging**
