### PR TITLE
[WIP] Full-scale test update

### LINKED ISSUE #1183: hello-world: update tests to v1.1.0
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/hello-world/canonical-data.json)

### LINKED ISSUE #1184: leap: update tests to v1.3.0
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/leap/canonical-data.json)

### LINKED ISSUE #1185: reverse-string: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/reverse-string/canonical-data.json)

### LINKED ISSUE #1186: pangram: update tests to v1.4.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/pangram/canonical-data.json)

### LINKED ISSUE #1187: rna-transcription: update tests to v1.2.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/rna-transcription/canonical-data.json)

### LINKED ISSUE #1188: hamming: update tests to v2.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/hamming/canonical-data.json)

### LINKED ISSUE #1189: word-count: update tests to v1.2.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/word-count/canonical-data.json)

### LINKED ISSUE #1190: gigasecond: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/gigasecond/canonical-data.json)

### LINKED ISSUE #1191: run-length-encoding: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/run-length-encoding/canonical-data.json)

### LINKED ISSUE #1192: meetup: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/meetup/canonical-data.json)

### LINKED ISSUE #1193: rotational-cipher: update tests to v1.2.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/rotational-cipher/canonical-data.json)

### LINKED ISSUE #1194: difference-of-squares: update tests to v1.2.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/difference-of-squares/canonical-data.json)

### LINKED ISSUE #1195: anagram: update tests to v1.2.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/anagram/canonical-data.json)

### LINKED ISSUE #1196: allergies: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/allergies/canonical-data.json)

### LINKED ISSUE #1197: robot-simulator: update tests to v2.2.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/robot-simulator/canonical-data.json)

### LINKED ISSUE #1198: sieve: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/sieve/canonical-data.json)

### LINKED ISSUE #1199: atbash-cipher: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/atbash-cipher/canonical-data.json)

### LINKED ISSUE #1200: sum-of-multiples: update tests to v1.2.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/sum-of-multiples/canonical-data.json)

### LINKED ISSUE #1201: acronym: update tests to v1.3.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/acronym/canonical-data.json)

### LINKED ISSUE #1202: say: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/say/canonical-data.json)

### LINKED ISSUE #1203: largest-series-product: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/largest-series-product/canonical-data.json)

### LINKED ISSUE #1204: kindergarten-garden: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/kindergarten-garden/canonical-data.json)

### LINKED ISSUE #1205: flatten-array: update tests to v1.2.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/flatten-array/canonical-data.json)

### LINKED ISSUE #1206: roman-numerals: update tests to v1.2.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/roman-numerals/canonical-data.json)

### LINKED ISSUE #1207: space-age: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/space-age/canonical-data.json)

### LINKED ISSUE #1208: luhn: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/luhn/canonical-data.json)

### LINKED ISSUE #1209: prime-factors: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/prime-factors/canonical-data.json)

### LINKED ISSUE #1210: pig-latin: update tests to v1.2.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/pig-latin/canonical-data.json)

### LINKED ISSUE #1211: scrabble-score: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/scrabble-score/canonical-data.json)

### LINKED ISSUE #1212: crypto-square: update tests to v3.2.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/crypto-square/canonical-data.json)

### LINKED ISSUE #1213: sublist: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/sublist/canonical-data.json)

### LINKED ISSUE #1214: circular-buffer: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/circular-buffer/canonical-data.json)

### LINKED ISSUE #1215: matrix: update tests to v1.0.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/matrix/canonical-data.json)

### LINKED ISSUE #1216: rail-fence-cipher: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/rail-fence-cipher/canonical-data.json)

### LINKED ISSUE #1217: nth-prime: update tests to v2.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/nth-prime/canonical-data.json)

### LINKED ISSUE #1218: saddle-points: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/saddle-points/canonical-data.json)

### LINKED ISSUE #1219: perfect-numbers: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/perfect-numbers/canonical-data.json)

### LINKED ISSUE #1220: secret-handshake: update tests to v1.2.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/secret-handshake/canonical-data.json)

### LINKED ISSUE #1221: twelve-days: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/twelve-days/canonical-data.json)

### LINKED ISSUE #1222: palindrome-products: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/palindrome-products/canonical-data.json)

### LINKED ISSUE #1223: bracket-push: update tests to v1.2.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/bracket-push/canonical-data.json)

### LINKED ISSUE #1224: minesweeper: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/minesweeper/canonical-data.json)

### LINKED ISSUE #1225: queen-attack: update tests to v2.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/queen-attack/canonical-data.json)

### LINKED ISSUE #1226: wordy: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/wordy/canonical-data.json)

### LINKED ISSUE #1227: phone-number: update tests to v1.4.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/phone-number/canonical-data.json)

### LINKED ISSUE #1228: ocr-numbers: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/ocr-numbers/canonical-data.json)

### LINKED ISSUE #1229: house: update tests to v2.0.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/house/canonical-data.json)

### LINKED ISSUE #1230: poker: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/poker/canonical-data.json)

### LINKED ISSUE #1231: zebra-puzzle: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/zebra-puzzle/canonical-data.json)

### LINKED ISSUE #1232: rectangles: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/rectangles/canonical-data.json)

### LINKED ISSUE #1233: binary-search: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/binary-search/canonical-data.json)

### LINKED ISSUE #1234: list-ops: update tests to v2.2.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/list-ops/canonical-data.json)

### LINKED ISSUE #1235: book-store: update tests to v1.3.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/book-store/canonical-data.json)

### LINKED ISSUE #1236: diamond: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/diamond/canonical-data.json)

### LINKED ISSUE #1237: variable-length-quantity: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/variable-length-quantity/canonical-data.json)

### LINKED ISSUE #1238: all-your-base: update tests to v2.3.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/all-your-base/canonical-data.json)

### LINKED ISSUE #1239: clock: update tests to v2.2.1
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/clock/canonical-data.json)

### LINKED ISSUE #1240: bowling: update tests to v1.2.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/bowling/canonical-data.json)

### LINKED ISSUE #1241: word-search: update tests to v1.2.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/word-search/canonical-data.json)

### LINKED ISSUE #1242: alphametics: update tests to v1.2.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/alphametics/canonical-data.json)

### LINKED ISSUE #1243: tournament: update tests to v1.4.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/tournament/canonical-data.json)

### LINKED ISSUE #1244: scale-generator: update tests to v1.0.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/scale-generator/canonical-data.json)

### LINKED ISSUE #1245: protein-translation: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/protein-translation/canonical-data.json)

### LINKED ISSUE #1246: change: update tests to v1.2.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/change/canonical-data.json)

### LINKED ISSUE #1247: two-fer: update tests to v1.2.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/two-fer/canonical-data.json)

### LINKED ISSUE #1248: collatz-conjecture: update tests to v1.2.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/collatz-conjecture/canonical-data.json)

### LINKED ISSUE #1249: complex-numbers: update tests to v1.3.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/complex-numbers/canonical-data.json)

### LINKED ISSUE #1250: two-bucket: update tests to v1.4.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/two-bucket/canonical-data.json)

### LINKED ISSUE #1251: markdown: update tests to v1.2.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/markdown/canonical-data.json)

### LINKED ISSUE #1252: forth: update tests to v1.5.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/forth/canonical-data.json)

### LINKED ISSUE #1253: food-chain: update tests to v2.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/food-chain/canonical-data.json)

### LINKED ISSUE #1254: zipper: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/zipper/canonical-data.json)

### LINKED ISSUE #1255: dominoes: update tests to v2.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/dominoes/canonical-data.json)

### LINKED ISSUE #1256: pov: update tests to v1.2.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/pov/canonical-data.json)

### LINKED ISSUE #1257: react: update tests to v1.1.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/react/canonical-data.json)

### LINKED ISSUE #1258: binary-search-tree: update tests to v1.0.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/binary-search-tree/canonical-data.json)

### LINKED ISSUE #1259: custom-set: update tests to v1.3.0
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/custom-set/canonical-data.json)

### PR DESCRIPTION
**Pull request by mRcfps**
Updates with nothing changed, such as applying new input policy, correcting naming styles, etc:

- [x] hello-world: Fix #1183 
- [x] leap: Fix #1184 
- [x] reverse-string: Fix #1185 
- [x] pangram: Fix #1186 
- [x] hamming: Fix #1188 
- [x] word-count: Fix #1189 
- [x] gigasecond: Fix #1190 
- [x] run-length-encoding: Fix #1191 
- [x] meetup: Fix #1192 
- [x] rotational-cipher: Fix #1193 
- [x] difference-of-squares: Fix #1194 
- [x] allergies: Fix #1196 
- [x] robot-simulator: Fix #1197 
- [x] sieve: Fix #1198 
- [x] atbash-cipher: Fix #1199 
- [x] sum-of-multiples: Fix #1200 
- [x] say: Fix #1202 
- [x] largest-series-product: Fix #1203 
- [x] kindergarten-garden: Fix #1204 
- [x] flatten-array: Fix #1205 
- [x] space-age: Fix #1207 
- [x] luhn: Fix #1208 
- [x] prime-factors: Fix #1209 
- [x] pig-latin: Fix #1210 
- [x] scrabble-score: Fix #1211 
- [x] crypto-square: Fix #1212 
- [x] sublist: Fix #1213 
- [x] circular-buffer: Fix #1214 
- [x] rail-fence-cipher: Fix #1216 
- [x] nth-prime: Fix #1217 
- [x] saddle-points: Fix #1218 
- [x] perfect-numbers: Fix #1219 
- [x] secret-handshake: Fix #1220  
- [x] palindrome-products: Fix #1222 
- [x] bracket-push: Fix #1223 
- [x] minesweeper: Fix #1224 
- [x] wordy: Fix #1226 
- [x] ocr-numbers: Fix #1228  
- [x] rectangles: Fix #1232 
- [x] binary-search: Fix #1233 
- [x] list-ops: Fix #1234 
- [x] diamond: Fix #1236 
- [x] variable-length-quantity: Fix #1237 
- [x] word-search: Fix #1241 
- [x] tournament: Fix #1243 
- [x] protein-translator: Fix #1245 
- [x] two-fer: Fix #1247  
- [x] two-bucket: Fix #1250 
- [x] markdown: Fix #1251 
- [x] forth: Fix #1252 
- [x] dominoes: Fix #1255 
- [x] custom-set: Fix #1259 

Updates with changes to tests:

- [x] rna-transcription: Fix #1187 
- [x] anagram: Fix #1195 
- [x] acronym: Fix #1201 
- [x] roman-numerals: Fix #1206 
- [x] matrix: Fix #1215 
- [x] twelve-days: Fix #1221
- [x] queen-attack: Fix #1225 
- [x] phone-number: Fix #1227 
- [x] house: Fix #1229 
- [x] poker: Fix #1230 
- [x] zebra-puzzle: Fix #1231
- [x] book-store: Fix #1235 
- [x] all-your-base: Fix #1238 
- [x] clock: Fix #1239 
- [x] bowling: Fix #1240 
- [x] alphametics: Fix #1242 
- [x] scale-generator: Fix #1244 
- [x] change: Fix #1246 
- [x] collatz-conjecture: Fix #1248
- [x] complex-numbers: Fix #1249 
- [x] food-chain: Fix #1253 
- [x] zipper: Fix #1254 
- [x] pov: Fix #1256 
- [ ] react: Fix #1257 
- [x] binary-search-tree: Fix #1258

### CODE REVIEW

**Comment by mRcfps** [comment]
@cmccandless While I'm working on updating tests, I've encountered two exercises that differ quite a lot from canonical data:

- **food-chain**: Currently there is even no concept of input in the Python implementation, but [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/food-chain/canonical-data.json) has input parameters `startVerse` and `endVerse`. Since this exercise resembles so much to [house](https://github.com/exercism/python/blob/master/exercises/house/house_test.py), should I adopt the same test style?
- **binary-search-tree**: It seems this exercise had been implemented before [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/binary-search-tree/canonical-data.json) was proposed, so a thorough discussion on updating this exercise is needed. Maybe a new PR?

**Comment by cmccandless** [comment]
@mRcfps 

> **food-chain**: Currently there is even no concept of input in the Python implementation, but [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/food-chain/canonical-data.json) has input parameters `startVerse` and `endVerse`. Since this exercise resembles so much to [house](https://github.com/exercism/python/blob/master/exercises/house/house_test.py), should I adopt the same test style?

Yes, I believe adopting a similar style to `house`, `twelve-days`, and `beer-song` would be the best practice.

> **binary-search-tree**: It seems this exercise had been implemented before [canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/binary-search-tree/canonical-data.json) was proposed, so a thorough discussion on updating this exercise is needed. Maybe a new PR?

Yes, I recall [commenting](https://github.com/exercism/python/pull/773#issuecomment-341437614) in #773 that canonical data was being implemented; I'm not sure why I didn't push then to wait until the data was merged to problem-specifications. I think a new PR would be the best practice.

I will review this PR once you've made the changes to `house`, but ordinarily separate PRs are preferred when different exercises are involved (the exception to this is when the same issue is being addressed in all exercises, such as [overhauling exception usage and handling](https://github.com/exercism/python/pull/1113)). Separate PRs make it easier for maintainers to review and selectively merge without having to wait on the entire batch of changes to pass review.

**Comment by mRcfps** [comment]
@cmccandless Separating PRs would be a better idea, and thank you for pointing this out. I'll keep this PR as a checklist, and close it when everything is done.

**Comment by mRcfps** [comment]
I think we're done with this wave of tests updates (except **react** for callback issues).

**Pull request closed without merging**
