### PR TITLE
all exercises: Add __init__.py files to exercise directories

### PR DESCRIPTION
**Pull request by wsgac**
Some environments (e.g. Elpy under Emacs) find it difficult to
properly import solution files to test files (at least when running
tests interactively) and to jump between definitions, unless exercise
directories are treated as modules.

### CODE REVIEW

**Comment by cmccandless** [comment]
I'm not sure how you're running the tests, but `pytest` does not require exercises to be modules and is the official way of running tests for this track. The issue you're describing sounds like it is specific to your individual development environment, and I don't think that environment-specific fixes necessarily belong here.

**Comment by wsgac** [comment]
Yes, it's kind of specific to Emacs/Elpy. It might (though I'm not sure) apply to other environments as well. I know that you can run individual test cases like this: `pytest <test_file>::<test_class>::<test_method>` which gives you some granularity, but sometimes I wanted to run tests from the Python REPL and having the `__init__.py` files there helped. I won't push though :).

**Comment by cmccandless** [comment]
Maintainers' Note: I'm marking as invalid for future reference; however, I don't feel that this label is as accurate as it could be (maybe something like `environment-specific` would be better?). Tagging #1095 for discussion on labels.

**Comment by cmccandless** [comment]
@wsgac I'm going to close this, since it won't be merged. Thank you for putting in the PR anyway; if someone raises this issue again, we'll reference this PR for a user-specific solution.

**Comment by wsgac** [comment]
Ok, thanks.

**Pull request closed without merging**
