### PR TITLE
robot-simulator: updated tests to v3.0.0

### LINKED ISSUE #1525: robot-simulator: update tests to v3.0.0
The [test suite](https://github.com/exercism/python/blob/master/exercises/robot-simulator/robot_simulator_test.py) for robot-simulator is out of date and needs updated to conform to the [latest canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/robot-simulator/canonical-data.json).

### PR DESCRIPTION
**Pull request by JuliaKBremer**
Updated tests to v2.3.0 , added Exception tests for invalid directions/instructions as well as tests for each direction the robot can go
Closes #1525

### CODE REVIEW

**Comment by cmccandless** [comment]
Please add [magic words](https://help.github.com/articles/closing-issues-using-keywords/) to your PR description to link this PR to issue #1525.

**Comment by cmccandless** [comment]
Also, it appears that since your changes, `robot-simulator` has been updated to 3.0.0. Please make the appropriate changes to move to 3.0.0.

**Comment by cmccandless** [comment]
Merged; thanks for working on this!

**Comment by JuliaKBremer** [comment]
Thank you for your time, help and patience!

**Pull request merged**
