### PR TITLE
Custom set add test template

### LINKED ISSUE #1940: custom-set: add test template
## Task
Create a test template file for `custom-set`

### Details
1. If this is your first time contributing to this repository, welcome!
    - Contributing to a repository on GitHub requires a [fork](https://help.github.com/en/articles/fork-a-repo)
1. Create a branch on your local repository called `custom-set-add-test-template`
    - Run: `git checkout -b custom-set-add-test-template`
1. Clone problem-specifications repository; this is used to populate the template
    - Run: `git clone https://github.com/exercism/problem-specifications ../problem-specifications`
1. Create `exercises/custom-set/.meta/template.j2`
    - See [Generator Documentation] for more information
1. Generate test file from new template
    - Run: `bin/generate_tests.py custom-set`

At this point, if the generator fails, or you are otherwise stuck,
please feel free to reach out! It is perfectly acceptable to submit
an incomplete PR in order to get feedback or assistance.

### Resources
- [Contributing Guide]
- [Generator Documentation]
- [Closing issues using keywords]

[Contributing Guide]: https://github.com/exercism/python/blob/master/docs/CONTRIBUTING.md
[Generator Documentation]: https://github.com/exercism/python/blob/master/docs/GENERATOR.md
[Closing issues using keywords]: https://help.github.com/en/articles/closing-issues-using-keywords

### PR DESCRIPTION
**Pull request by tqa236**
Resolve #1940. The test template is correct but very repetitive. It would be nice if someone can help me refactor it.

- I would like to create a local macros to use in the test template but I don't know how to import it. Can anyone help me?
- How to strip the unnecessary newline?

### CODE REVIEW

**Comment by tqa236** [comment]
I know. I'm asking how to do that :)). I don't know how to import a new macros file into the test template.

**Comment by yawpitch** [comment]
> I know. I'm asking how to do that :)). I don't know how to import a new macros file into the test template.

You should be able to import the local macros with something like this:

```
{%- import "local_macros.j2" as local_macros -%}
```

As for the newline, that appears to be coming from lines 38 and 39:

```
        {%- endif %}
        {% if property == "add" -%}
```

You have to image in that _every_ logical tag _actually encountered_ in Jinja2 rendering will add a newline by default ... because you're deleting the leading whitespace on line 38 but _not_ trimming the trailing whitespace a newline gets added for that line  ... since line 39 _does not_ trim the leading whitespace that newline gets left in place.

What I usually do is start by _never_ trimming leading whitespace and _always_ trimming trailing whitespace on the if, elif, else, end, for, endfor, etc tags -- any tag that doesn't produce text itself, but just determines the logic flow -- which you don't usually want adding whitespace for themselves.

**Comment by cmccandless** [comment]
> I know. I'm asking how to do that :)). I don't know how to import a new macros file into the test template.

You can also declare new macros in the same template file as they are used.

**Comment by tqa236** [comment]
@yawpitch  Thank you, I can trim the newline now. But I cannot import the local macros despite trying various ways.

Here's the error:

```
DEBUG:generator:custom-set: attempting render
DEBUG:generator:custom_set/.meta/local_macros.j2
INFO:generator:custom-set: no template found; skipping
```

But if adding new macros to the common file is fine for @cmccandless , I'll do that for the sake of simplicity. 

Can you both check the new commit? Each property now is just one line of code so I don't create macros for them.

**Pull request merged**
