### PR TITLE
Add test to confirm all letters are checked.

### PR DESCRIPTION
**Pull request by chivalry**
My attempt to address issue #2190

### CODE REVIEW

**Comment by chivalry** [comment]
Any help on this would be appreciated. I've looked at the failed checks but don't understand what I messed up.

**Comment by khoivan88** [comment]
It is not you, it just requires others to approve it. Another thing you can do is python 3 has string.ascii_lowercase. so you can do something like:
```python
import string

...
for char in string.ascii_lowercase:
    # do something
...
```

**Comment by AnAccountForReportingBugs** [comment]
The build is failing because `pangram` uses a template and [canonical data](https://github.com/exercism/problem-specifications/tree/master/exercises/pangram). Instead of editing the test file directly, you should follow the directions in the [contributing guide](https://github.com/exercism/python/blob/master/CONTRIBUTING.md) to add the test that way. Although, I'm not sure how exactly this test would fit in there, as Jinja2 is not my strong suit. If a test like this were approved, the use of [subTest](https://docs.python.org/3/library/unittest.html#subtests) would make the tracebacks clearer for those implementing the exercise.

**Comment by khoivan88** [comment]
so, if I am correct, @chivalry , you would need to change [`canonical-data.json`](https://github.com/exercism/problem-specifications/blob/master/exercises/pangram/canonical-data.json) by adding this at the near the end:
```json
,
    {
      "description": "missing letter z",
      "property": "isPangram",
      "input": {
        "sentence": "The quick brown fox jumps over the layy dog"
      },
      "expected": false
    }
```

**Comment by chivalry** [comment]
Thanks to both of you. I'll look more closely at the contributing guide and try again today.

**Comment by chivalry** [comment]
Well, I delved into the contributing guide, and begin to see the problem. This isn't an issue with just the Python track, but with all the tracks. To really fix it would require editing not only the problem specifications, but all of the Jinja templates as well. This one's probably above my head, but I'll look into it a bit more.

**Comment by khoivan88** [comment]
This text quoted below (found [here](https://github.com/exercism/docs/blob/master/contributing-to-language-tracks/README.md#test-suites)) seems to address how you would go about suggesting test that would affect all tracks:
> For every change that you make to the test suite, ask yourself: Should this change also affect other language tracks that implement the same exercise?
> If you think it might, open a discussion in the problem-specifications repository and get other track implementors' feedback on the subject.
> If this change should affect the broader Exercism curriculum, then use the issue in problem-specifications to:
> - Hash out all the details together.
> - Figure out the necessary changes to the canonical-data.json for the exercise (if it exists).
> - Draft an issue that can be submitted to all the tracks that implement the exercise using the blazon tool (which automates the tedious parts). More about that here.

**Comment by cmccandless** [comment]
@chivalry The fastest approach to resolving this issue would be to create a track-specific test here, and also open a pull request to add test(s) to problem-specifications. Once that merges, the track-specific tests could be removed; this is not likely to happen soon as the problem-specifications repo is currently frozen while the v3 redesign is underway.

The test as you have written it does not easily transition into the template format, but I have created #2192 to show another approach that should address the gap you have pointed out in #2190. Please take a look at that PR and let me know what you think.

**Pull request closed without merging**
