### PR TITLE
robot-simulator: add parameters to exercise placeholder

### LINKED ISSUE #622: robot-simulator: add parameters to exercise placeholder
We would like you to help us add expected parameters in placeholder templates as described in #509 to make it easier for learners to start working on the exercise in question.

Feel free to ask any questions, we'll be glad to help!

### PR DESCRIPTION
**Pull request by parinporecha**
Resolves #622

### CODE REVIEW

**Comment by N-Parsons** [comment]
I'm really not keen on having default values for the bearings. There are other ways to implement bearings that can actually be quite useful, so I don't think that we should push people down one route.

For an example of an alternative, see [my solution](http://exercism.io/submissions/ea15ff22414b4c8d971a0aef6a4d43db).

**Comment by parinporecha** [comment]
@N-Parsons I think you're right. I've made a commit setting the bearing enums to strings -

```
# Globals for the bearings
EAST = "East"
NORTH = "North"
WEST = "West"
SOUTH = "South"
```
Let me know if this is okay.

**Comment by N-Parsons** [comment]
@parinporecha, my point was more that giving any value to the bearings in the exercise suggests that that's how they should be handled, particularly to new programmers.

In this exercise, there are actually a number of ways that the bearing values can be useful, so I think part of the exercise should be deciding what these values should be.

For example, I used the following for my solution (with sine and cosine):
```
EAST = 0
NORTH = 90
WEST = 180
SOUTH = 270
```

But I've also seen equally valid and sensible solutions using tuples of (dx, dy):
```
EAST = (1, 0)
NORTH = (0, 1)
WEST = (-1, 0)
SOUTH = (0, -1)
```

I don't think that the exercise should favour any one of these solutions.

Ultimately, it's not the end of the world if there are pre-assigned values (people can just change them), but I still feel like it takes away some freedom and creativity.

**Comment by m-a-ge** [comment]
This is a good discussion.
I personally believe it's more important to provide default params, even though it might encourage people to use certain way of solving the exercise over the other. Sometimes you just out of ideas how to organize things and need a direction, without direction you'll tend to drop the exercise.

In this particular case, I suggest declaring variables as:
```python
EAST = None
NORTH = None
WEST = None
SOUTH = None
```
and let the learner decide on their representation.

What do you think?

**Comment by N-Parsons** [comment]
@m-a-ge, I think your solution strikes a good balance. It gives people the variable names in the way that the tests require, while leaving it to them to choose the values.

**Comment by parinporecha** [comment]
Sounds good @m-a-ge @N-Parsons

**Comment by m-a-ge** [comment]
@N-Parsons thanks for your insightful comments

@parinporecha thanks for your work. It's a best practice to squash your commits https://github.com/exercism/docs/blob/master/contributing/git-basics.md#squashing. It isn't a big deal since I can do it myself, but it would be awesome to just click on 'Merge pull request' button 😃 

Please note that there are some special ['closing issue' keywords](https://help.github.com/articles/closing-issues-using-keywords/) that you can put in description of your PR and Github will take care of closing the corresponding issue automatically after merge. 
It makes our work much easier. I hope this hint will help you to make your future PRs a bit better

**Comment by parinporecha** [comment]
@m-a-ge Sure, I'll keep that in mind for the future. Thanks for reviewing!

**Pull request merged**
