### PR TITLE
Added parameters to wordy ,word-count ,variables-length-quantity ,two-fer ,twelve-days ,trinary ,triangle ,transpose and tournamnet

### LINKED ISSUE #654: wordy: add parameters to exercise placeholder
We would like you to help us add expected parameters in placeholder templates as described in #509 to make it easier for learners to start working on the exercise in question.

Feel free to ask any questions, we'll be glad to help!

### PR DESCRIPTION
**Pull request by mikeyny**
Fixes #654 #652 #651 #650  #649 #648 #647 #644 #645 #646

### CODE REVIEW

**Comment by m-a-ge** [comment]
@mikeyny, thanks for your PR

As I mentioned in https://github.com/exercism/python/pull/631#issuecomment-333758748 I've intentionally created a separate issue for each exercise for the following reasons:

1. to encourage new contributions and promote Exercism during Hacktoberfest
1. having a separate issue for each exercise makes it easier to review them and discuss changes
1. it's relatively easier to track the progress that way in #509

Does it makes sense?

Sorry for inconvenience and hope to see separate PRs if possible

**Comment by mikeyny** [comment]
Hy @m-a-ge 

Sorry i'm a bit new to the world of open source , i had seen the separate issues but i thought i could fix with 1 pull request ,as i mentioned in the comment.

Will try and submit seperate pull request but i'm not exactly sure how to go about .

**Comment by m-a-ge** [comment]
@mikeyny I'm glad to hear that you are new to open source world, welcome 😃 

What exactly confuses you, could you clarify?

The best course of action in your case (since you used `master` branch to create this PR) would be to backup your work somewhere and leave changes related to only one exercise and push them forcefully. After that you can update PR's title and description accordingly. It's somewhat complicated approach, but it will leave this PR open.

It's a best practice to create a separate branches whenever you develop something and never work or push directly to **`master`** branch, it has a special meaning

Feel free to ask any questions

**Comment by mikeyny** [comment]
@m-a-ge  thanks a lot

I have started creating seperate branches for each issue i'm working on. Learned some new git 👍 .I managed to submit a few seperate pull requests ,really hoping you'll merge.

**Comment by m-a-ge** [comment]
@mikeyny I'm glad to hear that. Please note that It'll take some time for me to go through all open PRs

**Comment by mikeyny** [comment]
@m-a-ge  thats alright ,I noticed this repo now has a large amount of pull requests . I'm just glad have contributed & participated in hacktoberfest .

**Comment by m-a-ge** [comment]
@mikeyny 👍 
Don't you mind closing this PR?

**Pull request closed without merging**
