### PR TITLE
[Meltdown Mitigation]: Housekeeping. added space on line 69 in test.

### PR DESCRIPTION
**Pull request by Metallifax**
Noticed the missing space while working on the exercise, confirmed it with Flake8.

### CODE REVIEW

**Comment by BethanyG** [comment]
@Metallifax  -- We formatted those indents that way for a reason.  We use yapf, not black.  Please revert.  Thanks!

**Comment by BethanyG** [comment]
@Metallifax -- Once I was done fixing the failing CI, I was going to accept your first change.  Now that the CI is fixed, would you care to re-submit the space change?

**Comment by Metallifax** [comment]
@BethanyG My apologies, I gathered from the checklists and such that this was a flake8 or pylint style based on the configs. I'll keep this in mind, I hope I'm not too much of a burden, I'm a super new contributor.

I'll go ahead and re-submit that change now and study up on yapf.

**Comment by BethanyG** [comment]
@Metallifax --  no worries!  There is a lot to wade through with Exercism, and our repo for Python is .. a lot.  😄 

The [contributing guide](https://github.com/exercism/python/blob/main/CONTRIBUTING.md)  has a lot of Python track info, and the [contributing docs](https://exercism.org/docs/building) have a ton on Exercism in general.

For linting, spellchecking, and other formatting -- we periodically run linting reviews if we think that recent changes have introduced chaos.  And we encourage using all those tools when creating or doing heavy edits to exercises.  But we generally discourage contributors from running those en-mass as a bug hunt.  It's much easier to periodically do it when things are quiet, and have incremental PRs for bugs as people notice things are wrong.

**Pull request closed without merging**
