### PR TITLE
[PR2429 Reconstruction]

### PR DESCRIPTION
**Pull request by BethanyG**
Reconstructed [PR2429](https://github.com/exercism/python/pull/2429), so that the ugly merge commit files were omitted.  This PR should be "clean" and only include the additions/edits relating to the `Meltdown Mitigation` (conditionals) concept exercise 'cleanup':

Renamed exercise to `Meltdown Mitigation`.  Stub files reman as `conditionals.py` and `conditionals_test.py`.

- Rewrote `introduction.md`
- Rewrote `instructions.md`
- Created `hints.md`
- Created `exemplar.py`
- Checked and edited `conditionals_test.py`
- Added docstrings to `conditionals.py`
- Added a `/.meta/links.json` file
- Added `meltdown-mitigation` to track `config.json`
- Formatted `.meta/config.json` file
- Ran prettier

**Please Note:**  @sachsom95 and @neenjaw gave feedback on the original PR, so should have credit for review here as well.

### CODE REVIEW

**Review by neenjaw — APPROVED** [review]

**Comment by BethanyG** [comment]
Thank you @neenjaw!  😄

**Comment by BethanyG** [comment]
@iHiD / @ErikSchierboom  -- on review, flagging this as major.  Since this is a reproduction of [PR 2429](https://github.com/exercism/python/pull/2429), extra rep should also go to @sachsom95 for both the original exercise, and extra review on the re-write.

**Comment by iHiD** [comment]
(We have no way to automatically retrospectively append these reps, but if you make me a list across all the PRs, I'll manually go through and add them all at ETL time?)

**Comment by ErikSchierboom** [comment]
If I get a list of repo/PR number/label, I can do that automatically.

**Comment by BethanyG** [comment]
Thanks -- I'll make sure to add this to my "do before launch" list.  😄

**Pull request merged**
