### PR TITLE
Add aldraco as maintainer.

### PR DESCRIPTION
**Pull request by aldraco**

### CODE REVIEW

**Comment by cmccandless** [comment]
@aldraco the CI build failed because the `bob` exercise is out of date (related: #1920). Would you mind resolving this in a separate PR? See #2166 for details.

**Comment by aldraco** [comment]
Happy to! Should be able to look sometime today.

**Comment by aldraco** [comment]
OK, https://github.com/exercism/python/pull/2167 should get the build green again. Watching it now. :)

**Comment by yawpitch** [comment]
Done, now that #2167 is merged. Welcome aboard!

**Pull request merged**
