### PR TITLE
Remove Blocking (and Nonexistent) Prerequisites from Config.json

### PR DESCRIPTION
**Pull request by BethanyG**
Removed blocking and TBD Prerequisite Concept exercises from `config.json`.  Moved the existing `config.json` to `reference/IDEA_config.json` for a ref. as we add future exercises.

### CODE REVIEW

**Review by verdammelt — APPROVED** [review]
I skimmed the change and i guess it looks good. I had to do similar on my track before launch.

**Review by SleeplessByte — APPROVED** [review]
Didn't skim

**Comment by BethanyG** [comment]
Thank you both!

**Comment by kotp** [comment]
Got here after it was merged, but looks good!

**Pull request merged**
