### PR TITLE
[Space Age]: Update introduction and instructions

### PR DESCRIPTION
**Pull request by AndrewLawendy**
I submitted this PR because I found it challenging to understand the task solely through the provided instructions. In my experience, relying solely on test cases to understand a task may not be the most effective approach for students. Therefore, I hope that my contributions can help clarify the task for future students.

### CODE REVIEW

**Comment by AndrewLawendy** [comment]
Hi @BethanyG, I'm confused as to how my previous PR was not automatically closed by the bot. I would appreciate it if you could take a look and let me know if there are any changes I need to make. If you find the PR to be useful, please consider reopening it so we can continue the discussion.

**Comment by BethanyG** [comment]
To tag on to my previous comment - if there is something needed for instructions that is track or **_language specific_**, it can be included in a track _instruction append_ that gets automatically merged into instructions on the website.  That is what we did for your numbers information for `gigasecond` in the previous PR.

We might consider the "standard"  _"a class is needed for this exercise"_ append for this exercise.  Something similar to [this](https://github.com/exercism/python/blob/main/exercises/practice/matrix/.docs/instructions.append.md) or [this](https://github.com/exercism/python/blob/main/exercises/practice/grade-school/.docs/instructions.append.md).

So if you'd like to re-work your information into an instruction append, I would gladly review and reopen this PR.

**Comment by AndrewLawendy** [comment]
I would love to

**Comment by AndrewLawendy** [comment]
@BethanyG I pushed the changes

**Comment by AndrewLawendy** [comment]
On another note @BethanyG this [approach](https://exercism.org/tracks/python/exercises/collatz-conjecture/approaches/recursion) is problematic

The way it returns is not ideal and should not be encouraged or taught to student, this will lead to tail recursion.
You can find an ideal way of recursion here https://exercism.org/tracks/python/exercises/collatz-conjecture/solutions/bobahop.

Do you think this is worth opening an pr for?

**Comment by BethanyG** [comment]
@AndrewLawendy  -- Let's keep the discussion to one exercise/change/problem per PR/issue, please.  This PR is about `Space Age` and not `Collatz Conjecture`.   If you'd like to discuss the approach for `Collatz Conjecture`, you should open a separate PR or issue for it. 😄 

Otherwise, things can get messy and hard to track.  _Many thanks!_

**Comment by AndrewLawendy** [comment]
Hey @BethanyG , just checking if you need any change?

**Comment by BethanyG** [comment]
@AndrewLawendy  - I haven't had time to review this yet, and probably won't get to it until this weekend.  Please bear with me.  Thanks!

**Comment by BethanyG** [comment]
@AndrewLawendy  - I went ahead and added some links to the Python docs.  If this all looks good to you, let me know and I will merge.  Thanks!

**Review by BethanyG — APPROVED** [review]

**Comment by AndrewLawendy** [comment]
@BethanyG I like what you did

**Pull request merged**
