### PR TITLE
Add workflow for running the test generator on a PR

### PR DESCRIPTION
**Pull request by cmccandless**
Trigger with /generate-tests

### CODE REVIEW

**Comment by BethanyG** [comment]
Jeez -- such an impatient bot!  😉   @cmccandless -- assuming you are still ruminating, so removing the abandoned flag.

**Comment by BethanyG** [comment]
Well, here is a ➕  for the stale bot -- it did manage to mark this stale with the emoji label, and not freak out.  😄   Down side is that I think we're still working on this.  @cmccandless   lmk if that is not the case, and I can close it.

**Comment by cmccandless** [comment]
Would still like to get back to it, so leave open for now please. There's been dinner significant changes to tooling, so I may have to rewrite anyway, but I'd like to leave it open for reference.

**Comment by neenjaw** [comment]
Bad bot

**Comment by BethanyG** [comment]
Still active. Bad Bot!

**Pull request closed without merging**
