### PR TITLE
Add `Sets` Concept Documents

### PR DESCRIPTION
**Pull request by BethanyG**
Created the following docs for the `set` concept:
- `concepts/sets/.meta/config.json`
- `concepts/sets/about.md`
- `concepts/sets/introduction.md`
- `concepts/sets/links.json`
- `exercises/concept/sets/.meta/design.md`

### CODE REVIEW

**Comment by BethanyG** [comment]
Linting is failing due to `/home/runner/work/python/python/exercises/shared/.docs`.  #2475 needs to be merged ahead of this PR to correct that problem (_I think_).

**Comment by kotp** [comment]
> Linting is failing due to `/home/runner/work/python/python/exercises/shared/.docs`. #2475 needs to be merged ahead of this PR to correct that problem (_I think_).

That is merged, still a problem with the CI?

**Review by kotp — APPROVED** [review]
There seems to be some extra newlines, more than what seems to be the style in areas.  Not a reason to deny, but I wanted to mention it, if it is worth standardizing that.

**Comment by BethanyG** [comment]
> There seems to be some extra newlines, more than what seems to be the style in areas. Not a reason to deny, but I wanted to mention it, if it is worth standardizing that.

Thanks for the review.  😄     I'll take a look at the newlines across exercises at some point.  Most of the content needs to be re-edited to a shorter length anyways.

> That is merged, still a problem with the CI?

Yeah - there was a late addition to this PR  for `links.json`, so I needed to do a 3-way merge locally and force an update.  Things look ok now tho.

**Pull request merged**
