### PR TITLE
[WIP] Implement exercise #737 ledger

### LINKED ISSUE #737: ledger: implement exercise
There are exercises that are not yet implemented in Python track (the full list of them - https://github.com/exercism/python/issues/417#issuecomment-334841778).
You can help us change this situation by implementing this one. Ref #417

The guide ["Implement an exercise from specification"](https://github.com/exercism/docs/blob/master/you-can-help/implement-an-exercise-from-specification.md) will help you succeed.

If you still have questions, I encourage you to ask them before starting working on the issue.

I also suggest claiming the issue by creating an empty PR as stated [here](https://github.com/exercism/docs/blob/master/you-can-help/implement-an-exercise-from-specification.md#avoiding-duplicate-work)

Please note that there are some special ['closing issue' keywords](https://help.github.com/articles/closing-issues-using-keywords/) that you can put in description of your PR and Github will take care of closing the corresponding issue automatically after merge.
This simple thing helps us a lot, and makes our life a bit easier

### PR DESCRIPTION
**Pull request by thejessleigh**
Resolves #737 //m-a-ge

### CODE REVIEW

**Comment by m-a-ge** [comment]
@thejessleigh, are you still working on this?

**Comment by thejessleigh** [comment]
@m-a-ge Yes. Sorry. Got a bit bogged down during the week. Hoping to have something up tomorrow.

**Comment by cmccandless** [comment]
@thejessleigh are you still working on this?

**Comment by thejessleigh** [comment]
I'll go ahead and close this. I want to work on this but I keep not finding time. I'll try to come back to another exercise soon. Sorry.

**Comment by m-a-ge** [comment]
@thejessleigh 😉

**Pull request closed without merging**
