### PR TITLE
Minor simplification to is_pangram in the Bit field approach

### PR DESCRIPTION
**Pull request by hansonchar**

### CODE REVIEW

**Comment by BethanyG** [comment]
@bobahop  -- Going to defer to you here, since you are the author of the approach.
If you'd prefer not to pull this in, feel free to comment/close.  Thanks!

**Comment by BethanyG** [comment]
@iHiD  - tagging you as well, given the discussion in Discord.

**Comment by BethanyG** [comment]
Nevermid.  I am going to go ahead and merge this.  😄   Scream if I've done that in error!

**Review by BethanyG — APPROVED** [review]
Thank you for submitting this!  🎉

**Comment by hansonchar** [comment]
👍

**Comment by iHiD** [comment]
> Nevermid. I am going to go ahead and merge this. 😄 Scream if I've done that in error!

I like this version of @BethanyG 😉 

---

Thanks @hansonchar!

**Comment by hansonchar** [comment]
LOL.  In some bookstores, they call it "biased for action" and make it a leadership principle ;)

**Comment by bobahop** [comment]
Thanks @hansonchar! I like your simplification a lot. Sorry I'm late, I no longer get e-mail notifications from GitHub, because I was getting too many, and I haven't been checking it manually because I've been busy moving.

**Pull request merged**
