### PR TITLE
Update check-exercises.py to Python 3

### LINKED ISSUE #1706: Use Python3 for test/check-exercises.py
Update the [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) to use `python3`

Please target the `drop-python2` branch in your pull request.

### PR DESCRIPTION
**Pull request by AnAccountForReportingBugs**
Fixes #1706
Changed shebang
Removed unnecessary print_function import

### CODE REVIEW

**Comment by AnAccountForReportingBugs** [comment]
Hmm, this seems to have pulled in the other changes made for some reason, even though I branched from drop-python2.  At least I thought I did....

**Comment by cmccandless** [comment]
Easiest way to fix this:
```Bash
# (Just in case)
git checkout patch-4
git branch BOOKMARK
# Change this if necessary
EXERCISM_REMOTE_NAME=upstream
git pull -f $EXERCISM_REMOTE_NAME drop-python2
git cherry-pick BOOKMARK
```

Verify your changes relevant to this PR are in your `patch-4` branch, then `git branch -D BOOKMARK; git push -f`

**Comment by AnAccountForReportingBugs** [comment]
I couldn't get your technique to work, so I just took a hammer and force pushed a new branch.

**Comment by cmccandless** [comment]
> I couldn't get your technique to work, so I just took a hammer and force pushed a new branch.

That works too!

**Comment by cmccandless** [comment]
Merged; thanks for working on this!

**Pull request merged**
